import type { Metadata } from 'next';
import * as React from 'react';
import './tokenami.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<React.PropsWithChildren>) {
  return (
    <html lang="en">
      <body className="theme-light">{children}</body>
    </html>
  );
}
