// This file is generated by npm run build:icons
  
  export type IconName =
	| "add-line"
	| "archive-stack-line"
	| "home-5-line"
	| "pause-fill"
	| "play-fill"
	| "play-large-fill"
	| "repeat-line"
	| "search-line"
	| "shuffle-line"
	| "skip-back-fill"
	| "skip-forward-fill"
	| "time-line"
	| "volume-up-line";
  