import {
  gray,
  mauve,
  slate,
  sage,
  olive,
  sand,
  gold,
  bronze,
  brown,
  yellow,
  amber,
  orange,
  tomato,
  red,
  ruby,
  crimson,
  pink,
  plum,
  purple,
  violet,
  iris,
  indigo,
  blue,
  cyan,
  teal,
  jade,
  green,
  grass,
  lime,
  mint,
  sky,
  grayA,
  mauveA,
  slateA,
  sageA,
  oliveA,
  sandA,
  goldA,
  bronzeA,
  brownA,
  yellowA,
  amberA,
  orangeA,
  tomatoA,
  redA,
  rubyA,
  crimsonA,
  pinkA,
  plumA,
  purpleA,
  violetA,
  irisA,
  indigoA,
  blueA,
  cyanA,
  tealA,
  jadeA,
  greenA,
  grassA,
  limeA,
  mintA,
  skyA,
  grayDark,
  mauveDark,
  slateDark,
  sageDark,
  oliveDark,
  sandDark,
  goldDark,
  bronzeDark,
  brownDark,
  yellowDark,
  amberDark,
  orangeDark,
  tomatoDark,
  redDark,
  rubyDark,
  crimsonDark,
  pinkDark,
  plumDark,
  purpleDark,
  violetDark,
  irisDark,
  indigoDark,
  blueDark,
  cyanDark,
  tealDark,
  jadeDark,
  greenDark,
  grassDark,
  limeDark,
  mintDark,
  skyDark,
  grayDarkA,
  mauveDarkA,
  slateDarkA,
  sageDarkA,
  oliveDarkA,
  sandDarkA,
  goldDarkA,
  bronzeDarkA,
  brownDarkA,
  yellowDarkA,
  amberDarkA,
  orangeDarkA,
  tomatoDarkA,
  redDarkA,
  rubyDarkA,
  crimsonDarkA,
  pinkDarkA,
  plumDarkA,
  purpleDarkA,
  violetDarkA,
  irisDarkA,
  indigoDarkA,
  blueDarkA,
  cyanDarkA,
  tealDarkA,
  jadeDarkA,
  greenDarkA,
  grassDarkA,
  limeDarkA,
  mintDarkA,
  skyDarkA,
  blackA,
  whiteA,
} from '@radix-ui/colors';

const shared = {
  black: '#000',
  black1a: blackA.blackA1,
  black2a: blackA.blackA2,
  black3a: blackA.blackA3,
  black4a: blackA.blackA4,
  black5a: blackA.blackA5,
  black6a: blackA.blackA6,
  black7a: blackA.blackA7,
  black8a: blackA.blackA8,
  black9a: blackA.blackA9,
  black10a: blackA.blackA10,
  black11a: blackA.blackA11,
  black12a: blackA.blackA12,

  white: '#fff',
  white1a: whiteA.whiteA1,
  white2a: whiteA.whiteA2,
  white3a: whiteA.whiteA3,
  white4a: whiteA.whiteA4,
  white5a: whiteA.whiteA5,
  white6a: whiteA.whiteA6,
  white7a: whiteA.whiteA7,
  white8a: whiteA.whiteA8,
  white9a: whiteA.whiteA9,
  white10a: whiteA.whiteA10,
  white11a: whiteA.whiteA11,
  white12a: whiteA.whiteA12,
};

const light = {
  ...gray,
  ...mauve,
  ...slate,
  ...sage,
  ...olive,
  ...sand,
  ...gold,
  ...bronze,
  ...brown,
  ...yellow,
  ...amber,
  ...orange,
  ...tomato,
  ...red,
  ...ruby,
  ...crimson,
  ...pink,
  ...plum,
  ...purple,
  ...violet,
  ...iris,
  ...indigo,
  ...blue,
  ...cyan,
  ...teal,
  ...jade,
  ...green,
  ...grass,
  ...lime,
  ...mint,
  ...sky,

  gray1a: grayA.grayA1,
  gray2a: grayA.grayA2,
  gray3a: grayA.grayA3,
  gray4a: grayA.grayA4,
  gray5a: grayA.grayA5,
  gray6a: grayA.grayA6,
  gray7a: grayA.grayA7,
  gray8a: grayA.grayA8,
  gray9a: grayA.grayA9,
  gray10a: grayA.grayA10,
  gray11a: grayA.grayA11,
  gray12a: grayA.grayA12,

  mauve1a: mauveA.mauveA1,
  mauve2a: mauveA.mauveA2,
  mauve3a: mauveA.mauveA3,
  mauve4a: mauveA.mauveA4,
  mauve5a: mauveA.mauveA5,
  mauve6a: mauveA.mauveA6,
  mauve7a: mauveA.mauveA7,
  mauve8a: mauveA.mauveA8,
  mauve9a: mauveA.mauveA9,
  mauve10a: mauveA.mauveA10,
  mauve11a: mauveA.mauveA11,
  mauve12a: mauveA.mauveA12,

  slate1a: slateA.slateA1,
  slate2a: slateA.slateA2,
  slate3a: slateA.slateA3,
  slate4a: slateA.slateA4,
  slate5a: slateA.slateA5,
  slate6a: slateA.slateA6,
  slate7a: slateA.slateA7,
  slate8a: slateA.slateA8,
  slate9a: slateA.slateA9,
  slate10a: slateA.slateA10,
  slate11a: slateA.slateA11,
  slate12a: slateA.slateA12,

  sage1a: sageA.sageA1,
  sage2a: sageA.sageA2,
  sage3a: sageA.sageA3,
  sage4a: sageA.sageA4,
  sage5a: sageA.sageA5,
  sage6a: sageA.sageA6,
  sage7a: sageA.sageA7,
  sage8a: sageA.sageA8,
  sage9a: sageA.sageA9,
  sage10a: sageA.sageA10,
  sage11a: sageA.sageA11,
  sage12a: sageA.sageA12,

  olive1a: oliveA.oliveA1,
  olive2a: oliveA.oliveA2,
  olive3a: oliveA.oliveA3,
  olive4a: oliveA.oliveA4,
  olive5a: oliveA.oliveA5,
  olive6a: oliveA.oliveA6,
  olive7a: oliveA.oliveA7,
  olive8a: oliveA.oliveA8,
  olive9a: oliveA.oliveA9,
  olive10a: oliveA.oliveA10,
  olive11a: oliveA.oliveA11,
  olive12a: oliveA.oliveA12,

  sand1a: sandA.sandA1,
  sand2a: sandA.sandA2,
  sand3a: sandA.sandA3,
  sand4a: sandA.sandA4,
  sand5a: sandA.sandA5,
  sand6a: sandA.sandA6,
  sand7a: sandA.sandA7,
  sand8a: sandA.sandA8,
  sand9a: sandA.sandA9,
  sand10a: sandA.sandA10,
  sand11a: sandA.sandA11,
  sand12a: sandA.sandA12,

  gold1a: goldA.goldA1,
  gold2a: goldA.goldA2,
  gold3a: goldA.goldA3,
  gold4a: goldA.goldA4,
  gold5a: goldA.goldA5,
  gold6a: goldA.goldA6,
  gold7a: goldA.goldA7,
  gold8a: goldA.goldA8,
  gold9a: goldA.goldA9,
  gold10a: goldA.goldA10,
  gold11a: goldA.goldA11,
  gold12a: goldA.goldA12,

  bronze1a: bronzeA.bronzeA1,
  bronze2a: bronzeA.bronzeA2,
  bronze3a: bronzeA.bronzeA3,
  bronze4a: bronzeA.bronzeA4,
  bronze5a: bronzeA.bronzeA5,
  bronze6a: bronzeA.bronzeA6,
  bronze7a: bronzeA.bronzeA7,
  bronze8a: bronzeA.bronzeA8,
  bronze9a: bronzeA.bronzeA9,
  bronze10a: bronzeA.bronzeA10,
  bronze11a: bronzeA.bronzeA11,
  bronze12a: bronzeA.bronzeA12,

  brown1a: brownA.brownA1,
  brown2a: brownA.brownA2,
  brown3a: brownA.brownA3,
  brown4a: brownA.brownA4,
  brown5a: brownA.brownA5,
  brown6a: brownA.brownA6,
  brown7a: brownA.brownA7,
  brown8a: brownA.brownA8,
  brown9a: brownA.brownA9,
  brown10a: brownA.brownA10,
  brown11a: brownA.brownA11,
  brown12a: brownA.brownA12,

  yellow1a: yellowA.yellowA1,
  yellow2a: yellowA.yellowA2,
  yellow3a: yellowA.yellowA3,
  yellow4a: yellowA.yellowA4,
  yellow5a: yellowA.yellowA5,
  yellow6a: yellowA.yellowA6,
  yellow7a: yellowA.yellowA7,
  yellow8a: yellowA.yellowA8,
  yellow9a: yellowA.yellowA9,
  yellow10a: yellowA.yellowA10,
  yellow11a: yellowA.yellowA11,
  yellow12a: yellowA.yellowA12,

  amber1a: amberA.amberA1,
  amber2a: amberA.amberA2,
  amber3a: amberA.amberA3,
  amber4a: amberA.amberA4,
  amber5a: amberA.amberA5,
  amber6a: amberA.amberA6,
  amber7a: amberA.amberA7,
  amber8a: amberA.amberA8,
  amber9a: amberA.amberA9,
  amber10a: amberA.amberA10,
  amber11a: amberA.amberA11,
  amber12a: amberA.amberA12,

  orange1a: orangeA.orangeA1,
  orange2a: orangeA.orangeA2,
  orange3a: orangeA.orangeA3,
  orange4a: orangeA.orangeA4,
  orange5a: orangeA.orangeA5,
  orange6a: orangeA.orangeA6,
  orange7a: orangeA.orangeA7,
  orange8a: orangeA.orangeA8,
  orange9a: orangeA.orangeA9,
  orange10a: orangeA.orangeA10,
  orange11a: orangeA.orangeA11,
  orange12a: orangeA.orangeA12,

  tomato1a: tomatoA.tomatoA1,
  tomato2a: tomatoA.tomatoA2,
  tomato3a: tomatoA.tomatoA3,
  tomato4a: tomatoA.tomatoA4,
  tomato5a: tomatoA.tomatoA5,
  tomato6a: tomatoA.tomatoA6,
  tomato7a: tomatoA.tomatoA7,
  tomato8a: tomatoA.tomatoA8,
  tomato9a: tomatoA.tomatoA9,
  tomato10a: tomatoA.tomatoA10,
  tomato11a: tomatoA.tomatoA11,
  tomato12a: tomatoA.tomatoA12,

  red1a: redA.redA1,
  red2a: redA.redA2,
  red3a: redA.redA3,
  red4a: redA.redA4,
  red5a: redA.redA5,
  red6a: redA.redA6,
  red7a: redA.redA7,
  red8a: redA.redA8,
  red9a: redA.redA9,
  red10a: redA.redA10,
  red11a: redA.redA11,
  red12a: redA.redA12,

  ruby1a: rubyA.rubyA1,
  ruby2a: rubyA.rubyA2,
  ruby3a: rubyA.rubyA3,
  ruby4a: rubyA.rubyA4,
  ruby5a: rubyA.rubyA5,
  ruby6a: rubyA.rubyA6,
  ruby7a: rubyA.rubyA7,
  ruby8a: rubyA.rubyA8,
  ruby9a: rubyA.rubyA9,
  ruby10a: rubyA.rubyA10,
  ruby11a: rubyA.rubyA11,
  ruby12a: rubyA.rubyA12,

  crimson1a: crimsonA.crimsonA1,
  crimson2a: crimsonA.crimsonA2,
  crimson3a: crimsonA.crimsonA3,
  crimson4a: crimsonA.crimsonA4,
  crimson5a: crimsonA.crimsonA5,
  crimson6a: crimsonA.crimsonA6,
  crimson7a: crimsonA.crimsonA7,
  crimson8a: crimsonA.crimsonA8,
  crimson9a: crimsonA.crimsonA9,
  crimson10a: crimsonA.crimsonA10,
  crimson11a: crimsonA.crimsonA11,
  crimson12a: crimsonA.crimsonA12,

  pink1a: pinkA.pinkA1,
  pink2a: pinkA.pinkA2,
  pink3a: pinkA.pinkA3,
  pink4a: pinkA.pinkA4,
  pink5a: pinkA.pinkA5,
  pink6a: pinkA.pinkA6,
  pink7a: pinkA.pinkA7,
  pink8a: pinkA.pinkA8,
  pink9a: pinkA.pinkA9,
  pink10a: pinkA.pinkA10,
  pink11a: pinkA.pinkA11,
  pink12a: pinkA.pinkA12,

  plum1a: plumA.plumA1,
  plum2a: plumA.plumA2,
  plum3a: plumA.plumA3,
  plum4a: plumA.plumA4,
  plum5a: plumA.plumA5,
  plum6a: plumA.plumA6,
  plum7a: plumA.plumA7,
  plum8a: plumA.plumA8,
  plum9a: plumA.plumA9,
  plum10a: plumA.plumA10,
  plum11a: plumA.plumA11,
  plum12a: plumA.plumA12,

  purple1a: purpleA.purpleA1,
  purple2a: purpleA.purpleA2,
  purple3a: purpleA.purpleA3,
  purple4a: purpleA.purpleA4,
  purple5a: purpleA.purpleA5,
  purple6a: purpleA.purpleA6,
  purple7a: purpleA.purpleA7,
  purple8a: purpleA.purpleA8,
  purple9a: purpleA.purpleA9,
  purple10a: purpleA.purpleA10,
  purple11a: purpleA.purpleA11,
  purple12a: purpleA.purpleA12,

  violet1a: violetA.violetA1,
  violet2a: violetA.violetA2,
  violet3a: violetA.violetA3,
  violet4a: violetA.violetA4,
  violet5a: violetA.violetA5,
  violet6a: violetA.violetA6,
  violet7a: violetA.violetA7,
  violet8a: violetA.violetA8,
  violet9a: violetA.violetA9,
  violet10a: violetA.violetA10,
  violet11a: violetA.violetA11,
  violet12a: violetA.violetA12,

  iris1a: irisA.irisA1,
  iris2a: irisA.irisA2,
  iris3a: irisA.irisA3,
  iris4a: irisA.irisA4,
  iris5a: irisA.irisA5,
  iris6a: irisA.irisA6,
  iris7a: irisA.irisA7,
  iris8a: irisA.irisA8,
  iris9a: irisA.irisA9,
  iris10a: irisA.irisA10,
  iris11a: irisA.irisA11,
  iris12a: irisA.irisA12,

  indigo1a: indigoA.indigoA1,
  indigo2a: indigoA.indigoA2,
  indigo3a: indigoA.indigoA3,
  indigo4a: indigoA.indigoA4,
  indigo5a: indigoA.indigoA5,
  indigo6a: indigoA.indigoA6,
  indigo7a: indigoA.indigoA7,
  indigo8a: indigoA.indigoA8,
  indigo9a: indigoA.indigoA9,
  indigo10a: indigoA.indigoA10,
  indigo11a: indigoA.indigoA11,
  indigo12a: indigoA.indigoA12,

  blue1a: blueA.blueA1,
  blue2a: blueA.blueA2,
  blue3a: blueA.blueA3,
  blue4a: blueA.blueA4,
  blue5a: blueA.blueA5,
  blue6a: blueA.blueA6,
  blue7a: blueA.blueA7,
  blue8a: blueA.blueA8,
  blue9a: blueA.blueA9,
  blue10a: blueA.blueA10,
  blue11a: blueA.blueA11,
  blue12a: blueA.blueA12,

  cyan1a: cyanA.cyanA1,
  cyan2a: cyanA.cyanA2,
  cyan3a: cyanA.cyanA3,
  cyan4a: cyanA.cyanA4,
  cyan5a: cyanA.cyanA5,
  cyan6a: cyanA.cyanA6,
  cyan7a: cyanA.cyanA7,
  cyan8a: cyanA.cyanA8,
  cyan9a: cyanA.cyanA9,
  cyan10a: cyanA.cyanA10,
  cyan11a: cyanA.cyanA11,
  cyan12a: cyanA.cyanA12,

  teal1a: tealA.tealA1,
  teal2a: tealA.tealA2,
  teal3a: tealA.tealA3,
  teal4a: tealA.tealA4,
  teal5a: tealA.tealA5,
  teal6a: tealA.tealA6,
  teal7a: tealA.tealA7,
  teal8a: tealA.tealA8,
  teal9a: tealA.tealA9,
  teal10a: tealA.tealA10,
  teal11a: tealA.tealA11,
  teal12a: tealA.tealA12,

  jade1a: jadeA.jadeA1,
  jade2a: jadeA.jadeA2,
  jade3a: jadeA.jadeA3,
  jade4a: jadeA.jadeA4,
  jade5a: jadeA.jadeA5,
  jade6a: jadeA.jadeA6,
  jade7a: jadeA.jadeA7,
  jade8a: jadeA.jadeA8,
  jade9a: jadeA.jadeA9,
  jade10a: jadeA.jadeA10,
  jade11a: jadeA.jadeA11,
  jade12a: jadeA.jadeA12,

  green1a: greenA.greenA1,
  green2a: greenA.greenA2,
  green3a: greenA.greenA3,
  green4a: greenA.greenA4,
  green5a: greenA.greenA5,
  green6a: greenA.greenA6,
  green7a: greenA.greenA7,
  green8a: greenA.greenA8,
  green9a: greenA.greenA9,
  green10a: greenA.greenA10,
  green11a: greenA.greenA11,
  green12a: greenA.greenA12,

  grass1a: grassA.grassA1,
  grass2a: grassA.grassA2,
  grass3a: grassA.grassA3,
  grass4a: grassA.grassA4,
  grass5a: grassA.grassA5,
  grass6a: grassA.grassA6,
  grass7a: grassA.grassA7,
  grass8a: grassA.grassA8,
  grass9a: grassA.grassA9,
  grass10a: grassA.grassA10,
  grass11a: grassA.grassA11,
  grass12a: grassA.grassA12,

  lime1a: limeA.limeA1,
  lime2a: limeA.limeA2,
  lime3a: limeA.limeA3,
  lime4a: limeA.limeA4,
  lime5a: limeA.limeA5,
  lime6a: limeA.limeA6,
  lime7a: limeA.limeA7,
  lime8a: limeA.limeA8,
  lime9a: limeA.limeA9,
  lime10a: limeA.limeA10,
  lime11a: limeA.limeA11,
  lime12a: limeA.limeA12,

  mint1a: mintA.mintA1,
  mint2a: mintA.mintA2,
  mint3a: mintA.mintA3,
  mint4a: mintA.mintA4,
  mint5a: mintA.mintA5,
  mint6a: mintA.mintA6,
  mint7a: mintA.mintA7,
  mint8a: mintA.mintA8,
  mint9a: mintA.mintA9,
  mint10a: mintA.mintA10,
  mint11a: mintA.mintA11,
  mint12a: mintA.mintA12,

  sky1a: skyA.skyA1,
  sky2a: skyA.skyA2,
  sky3a: skyA.skyA3,
  sky4a: skyA.skyA4,
  sky5a: skyA.skyA5,
  sky6a: skyA.skyA6,
  sky7a: skyA.skyA7,
  sky8a: skyA.skyA8,
  sky9a: skyA.skyA9,
  sky10a: skyA.skyA10,
  sky11a: skyA.skyA11,
  sky12a: skyA.skyA12,
};

const dark = {
  ...grayDark,
  ...mauveDark,
  ...slateDark,
  ...sageDark,
  ...oliveDark,
  ...sandDark,
  ...goldDark,
  ...bronzeDark,
  ...brownDark,
  ...yellowDark,
  ...amberDark,
  ...orangeDark,
  ...tomatoDark,
  ...redDark,
  ...rubyDark,
  ...crimsonDark,
  ...pinkDark,
  ...plumDark,
  ...purpleDark,
  ...violetDark,
  ...irisDark,
  ...indigoDark,
  ...blueDark,
  ...cyanDark,
  ...tealDark,
  ...jadeDark,
  ...greenDark,
  ...grassDark,
  ...limeDark,
  ...mintDark,
  ...skyDark,

  gray1a: grayDarkA.grayA1,
  gray2a: grayDarkA.grayA2,
  gray3a: grayDarkA.grayA3,
  gray4a: grayDarkA.grayA4,
  gray5a: grayDarkA.grayA5,
  gray6a: grayDarkA.grayA6,
  gray7a: grayDarkA.grayA7,
  gray8a: grayDarkA.grayA8,
  gray9a: grayDarkA.grayA9,
  gray10a: grayDarkA.grayA10,
  gray11a: grayDarkA.grayA11,
  gray12a: grayDarkA.grayA12,

  mauve1a: mauveDarkA.mauveA1,
  mauve2a: mauveDarkA.mauveA2,
  mauve3a: mauveDarkA.mauveA3,
  mauve4a: mauveDarkA.mauveA4,
  mauve5a: mauveDarkA.mauveA5,
  mauve6a: mauveDarkA.mauveA6,
  mauve7a: mauveDarkA.mauveA7,
  mauve8a: mauveDarkA.mauveA8,
  mauve9a: mauveDarkA.mauveA9,
  mauve10a: mauveDarkA.mauveA10,
  mauve11a: mauveDarkA.mauveA11,
  mauve12a: mauveDarkA.mauveA12,

  slate1a: slateDarkA.slateA1,
  slate2a: slateDarkA.slateA2,
  slate3a: slateDarkA.slateA3,
  slate4a: slateDarkA.slateA4,
  slate5a: slateDarkA.slateA5,
  slate6a: slateDarkA.slateA6,
  slate7a: slateDarkA.slateA7,
  slate8a: slateDarkA.slateA8,
  slate9a: slateDarkA.slateA9,
  slate10a: slateDarkA.slateA10,
  slate11a: slateDarkA.slateA11,
  slate12a: slateDarkA.slateA12,

  sage1a: sageDarkA.sageA1,
  sage2a: sageDarkA.sageA2,
  sage3a: sageDarkA.sageA3,
  sage4a: sageDarkA.sageA4,
  sage5a: sageDarkA.sageA5,
  sage6a: sageDarkA.sageA6,
  sage7a: sageDarkA.sageA7,
  sage8a: sageDarkA.sageA8,
  sage9a: sageDarkA.sageA9,
  sage10a: sageDarkA.sageA10,
  sage11a: sageDarkA.sageA11,
  sage12a: sageDarkA.sageA12,

  olive1a: oliveDarkA.oliveA1,
  olive2a: oliveDarkA.oliveA2,
  olive3a: oliveDarkA.oliveA3,
  olive4a: oliveDarkA.oliveA4,
  olive5a: oliveDarkA.oliveA5,
  olive6a: oliveDarkA.oliveA6,
  olive7a: oliveDarkA.oliveA7,
  olive8a: oliveDarkA.oliveA8,
  olive9a: oliveDarkA.oliveA9,
  olive10a: oliveDarkA.oliveA10,
  olive11a: oliveDarkA.oliveA11,
  olive12a: oliveDarkA.oliveA12,

  sand1a: sandDarkA.sandA1,
  sand2a: sandDarkA.sandA2,
  sand3a: sandDarkA.sandA3,
  sand4a: sandDarkA.sandA4,
  sand5a: sandDarkA.sandA5,
  sand6a: sandDarkA.sandA6,
  sand7a: sandDarkA.sandA7,
  sand8a: sandDarkA.sandA8,
  sand9a: sandDarkA.sandA9,
  sand10a: sandDarkA.sandA10,
  sand11a: sandDarkA.sandA11,
  sand12a: sandDarkA.sandA12,

  gold1a: goldDarkA.goldA1,
  gold2a: goldDarkA.goldA2,
  gold3a: goldDarkA.goldA3,
  gold4a: goldDarkA.goldA4,
  gold5a: goldDarkA.goldA5,
  gold6a: goldDarkA.goldA6,
  gold7a: goldDarkA.goldA7,
  gold8a: goldDarkA.goldA8,
  gold9a: goldDarkA.goldA9,
  gold10a: goldDarkA.goldA10,
  gold11a: goldDarkA.goldA11,
  gold12a: goldDarkA.goldA12,

  bronze1a: bronzeDarkA.bronzeA1,
  bronze2a: bronzeDarkA.bronzeA2,
  bronze3a: bronzeDarkA.bronzeA3,
  bronze4a: bronzeDarkA.bronzeA4,
  bronze5a: bronzeDarkA.bronzeA5,
  bronze6a: bronzeDarkA.bronzeA6,
  bronze7a: bronzeDarkA.bronzeA7,
  bronze8a: bronzeDarkA.bronzeA8,
  bronze9a: bronzeDarkA.bronzeA9,
  bronze10a: bronzeDarkA.bronzeA10,
  bronze11a: bronzeDarkA.bronzeA11,
  bronze12a: bronzeDarkA.bronzeA12,

  brown1a: brownDarkA.brownA1,
  brown2a: brownDarkA.brownA2,
  brown3a: brownDarkA.brownA3,
  brown4a: brownDarkA.brownA4,
  brown5a: brownDarkA.brownA5,
  brown6a: brownDarkA.brownA6,
  brown7a: brownDarkA.brownA7,
  brown8a: brownDarkA.brownA8,
  brown9a: brownDarkA.brownA9,
  brown10a: brownDarkA.brownA10,
  brown11a: brownDarkA.brownA11,
  brown12a: brownDarkA.brownA12,

  yellow1a: yellowDarkA.yellowA1,
  yellow2a: yellowDarkA.yellowA2,
  yellow3a: yellowDarkA.yellowA3,
  yellow4a: yellowDarkA.yellowA4,
  yellow5a: yellowDarkA.yellowA5,
  yellow6a: yellowDarkA.yellowA6,
  yellow7a: yellowDarkA.yellowA7,
  yellow8a: yellowDarkA.yellowA8,
  yellow9a: yellowDarkA.yellowA9,
  yellow10a: yellowDarkA.yellowA10,
  yellow11a: yellowDarkA.yellowA11,
  yellow12a: yellowDarkA.yellowA12,

  amber1a: amberDarkA.amberA1,
  amber2a: amberDarkA.amberA2,
  amber3a: amberDarkA.amberA3,
  amber4a: amberDarkA.amberA4,
  amber5a: amberDarkA.amberA5,
  amber6a: amberDarkA.amberA6,
  amber7a: amberDarkA.amberA7,
  amber8a: amberDarkA.amberA8,
  amber9a: amberDarkA.amberA9,
  amber10a: amberDarkA.amberA10,
  amber11a: amberDarkA.amberA11,
  amber12a: amberDarkA.amberA12,

  orange1a: orangeDarkA.orangeA1,
  orange2a: orangeDarkA.orangeA2,
  orange3a: orangeDarkA.orangeA3,
  orange4a: orangeDarkA.orangeA4,
  orange5a: orangeDarkA.orangeA5,
  orange6a: orangeDarkA.orangeA6,
  orange7a: orangeDarkA.orangeA7,
  orange8a: orangeDarkA.orangeA8,
  orange9a: orangeDarkA.orangeA9,
  orange10a: orangeDarkA.orangeA10,
  orange11a: orangeDarkA.orangeA11,
  orange12a: orangeDarkA.orangeA12,

  tomato1a: tomatoDarkA.tomatoA1,
  tomato2a: tomatoDarkA.tomatoA2,
  tomato3a: tomatoDarkA.tomatoA3,
  tomato4a: tomatoDarkA.tomatoA4,
  tomato5a: tomatoDarkA.tomatoA5,
  tomato6a: tomatoDarkA.tomatoA6,
  tomato7a: tomatoDarkA.tomatoA7,
  tomato8a: tomatoDarkA.tomatoA8,
  tomato9a: tomatoDarkA.tomatoA9,
  tomato10a: tomatoDarkA.tomatoA10,
  tomato11a: tomatoDarkA.tomatoA11,
  tomato12a: tomatoDarkA.tomatoA12,

  red1a: redDarkA.redA1,
  red2a: redDarkA.redA2,
  red3a: redDarkA.redA3,
  red4a: redDarkA.redA4,
  red5a: redDarkA.redA5,
  red6a: redDarkA.redA6,
  red7a: redDarkA.redA7,
  red8a: redDarkA.redA8,
  red9a: redDarkA.redA9,
  red10a: redDarkA.redA10,
  red11a: redDarkA.redA11,
  red12a: redDarkA.redA12,

  ruby1a: rubyDarkA.rubyA1,
  ruby2a: rubyDarkA.rubyA2,
  ruby3a: rubyDarkA.rubyA3,
  ruby4a: rubyDarkA.rubyA4,
  ruby5a: rubyDarkA.rubyA5,
  ruby6a: rubyDarkA.rubyA6,
  ruby7a: rubyDarkA.rubyA7,
  ruby8a: rubyDarkA.rubyA8,
  ruby9a: rubyDarkA.rubyA9,
  ruby10a: rubyDarkA.rubyA10,
  ruby11a: rubyDarkA.rubyA11,
  ruby12a: rubyDarkA.rubyA12,

  crimson1a: crimsonDarkA.crimsonA1,
  crimson2a: crimsonDarkA.crimsonA2,
  crimson3a: crimsonDarkA.crimsonA3,
  crimson4a: crimsonDarkA.crimsonA4,
  crimson5a: crimsonDarkA.crimsonA5,
  crimson6a: crimsonDarkA.crimsonA6,
  crimson7a: crimsonDarkA.crimsonA7,
  crimson8a: crimsonDarkA.crimsonA8,
  crimson9a: crimsonDarkA.crimsonA9,
  crimson10a: crimsonDarkA.crimsonA10,
  crimson11a: crimsonDarkA.crimsonA11,
  crimson12a: crimsonDarkA.crimsonA12,

  pink1a: pinkDarkA.pinkA1,
  pink2a: pinkDarkA.pinkA2,
  pink3a: pinkDarkA.pinkA3,
  pink4a: pinkDarkA.pinkA4,
  pink5a: pinkDarkA.pinkA5,
  pink6a: pinkDarkA.pinkA6,
  pink7a: pinkDarkA.pinkA7,
  pink8a: pinkDarkA.pinkA8,
  pink9a: pinkDarkA.pinkA9,
  pink10a: pinkDarkA.pinkA10,
  pink11a: pinkDarkA.pinkA11,
  pink12a: pinkDarkA.pinkA12,

  plum1a: plumDarkA.plumA1,
  plum2a: plumDarkA.plumA2,
  plum3a: plumDarkA.plumA3,
  plum4a: plumDarkA.plumA4,
  plum5a: plumDarkA.plumA5,
  plum6a: plumDarkA.plumA6,
  plum7a: plumDarkA.plumA7,
  plum8a: plumDarkA.plumA8,
  plum9a: plumDarkA.plumA9,
  plum10a: plumDarkA.plumA10,
  plum11a: plumDarkA.plumA11,
  plum12a: plumDarkA.plumA12,

  purple1a: purpleDarkA.purpleA1,
  purple2a: purpleDarkA.purpleA2,
  purple3a: purpleDarkA.purpleA3,
  purple4a: purpleDarkA.purpleA4,
  purple5a: purpleDarkA.purpleA5,
  purple6a: purpleDarkA.purpleA6,
  purple7a: purpleDarkA.purpleA7,
  purple8a: purpleDarkA.purpleA8,
  purple9a: purpleDarkA.purpleA9,
  purple10a: purpleDarkA.purpleA10,
  purple11a: purpleDarkA.purpleA11,
  purple12a: purpleDarkA.purpleA12,

  violet1a: violetDarkA.violetA1,
  violet2a: violetDarkA.violetA2,
  violet3a: violetDarkA.violetA3,
  violet4a: violetDarkA.violetA4,
  violet5a: violetDarkA.violetA5,
  violet6a: violetDarkA.violetA6,
  violet7a: violetDarkA.violetA7,
  violet8a: violetDarkA.violetA8,
  violet9a: violetDarkA.violetA9,
  violet10a: violetDarkA.violetA10,
  violet11a: violetDarkA.violetA11,
  violet12a: violetDarkA.violetA12,

  iris1a: irisDarkA.irisA1,
  iris2a: irisDarkA.irisA2,
  iris3a: irisDarkA.irisA3,
  iris4a: irisDarkA.irisA4,
  iris5a: irisDarkA.irisA5,
  iris6a: irisDarkA.irisA6,
  iris7a: irisDarkA.irisA7,
  iris8a: irisDarkA.irisA8,
  iris9a: irisDarkA.irisA9,
  iris10a: irisDarkA.irisA10,
  iris11a: irisDarkA.irisA11,
  iris12a: irisDarkA.irisA12,

  indigo1a: indigoDarkA.indigoA1,
  indigo2a: indigoDarkA.indigoA2,
  indigo3a: indigoDarkA.indigoA3,
  indigo4a: indigoDarkA.indigoA4,
  indigo5a: indigoDarkA.indigoA5,
  indigo6a: indigoDarkA.indigoA6,
  indigo7a: indigoDarkA.indigoA7,
  indigo8a: indigoDarkA.indigoA8,
  indigo9a: indigoDarkA.indigoA9,
  indigo10a: indigoDarkA.indigoA10,
  indigo11a: indigoDarkA.indigoA11,
  indigo12a: indigoDarkA.indigoA12,

  blue1a: blueDarkA.blueA1,
  blue2a: blueDarkA.blueA2,
  blue3a: blueDarkA.blueA3,
  blue4a: blueDarkA.blueA4,
  blue5a: blueDarkA.blueA5,
  blue6a: blueDarkA.blueA6,
  blue7a: blueDarkA.blueA7,
  blue8a: blueDarkA.blueA8,
  blue9a: blueDarkA.blueA9,
  blue10a: blueDarkA.blueA10,
  blue11a: blueDarkA.blueA11,
  blue12a: blueDarkA.blueA12,

  cyan1a: cyanDarkA.cyanA1,
  cyan2a: cyanDarkA.cyanA2,
  cyan3a: cyanDarkA.cyanA3,
  cyan4a: cyanDarkA.cyanA4,
  cyan5a: cyanDarkA.cyanA5,
  cyan6a: cyanDarkA.cyanA6,
  cyan7a: cyanDarkA.cyanA7,
  cyan8a: cyanDarkA.cyanA8,
  cyan9a: cyanDarkA.cyanA9,
  cyan10a: cyanDarkA.cyanA10,
  cyan11a: cyanDarkA.cyanA11,
  cyan12a: cyanDarkA.cyanA12,

  teal1a: tealDarkA.tealA1,
  teal2a: tealDarkA.tealA2,
  teal3a: tealDarkA.tealA3,
  teal4a: tealDarkA.tealA4,
  teal5a: tealDarkA.tealA5,
  teal6a: tealDarkA.tealA6,
  teal7a: tealDarkA.tealA7,
  teal8a: tealDarkA.tealA8,
  teal9a: tealDarkA.tealA9,
  teal10a: tealDarkA.tealA10,
  teal11a: tealDarkA.tealA11,
  teal12a: tealDarkA.tealA12,

  jade1a: jadeDarkA.jadeA1,
  jade2a: jadeDarkA.jadeA2,
  jade3a: jadeDarkA.jadeA3,
  jade4a: jadeDarkA.jadeA4,
  jade5a: jadeDarkA.jadeA5,
  jade6a: jadeDarkA.jadeA6,
  jade7a: jadeDarkA.jadeA7,
  jade8a: jadeDarkA.jadeA8,
  jade9a: jadeDarkA.jadeA9,
  jade10a: jadeDarkA.jadeA10,
  jade11a: jadeDarkA.jadeA11,
  jade12a: jadeDarkA.jadeA12,

  green1a: greenDarkA.greenA1,
  green2a: greenDarkA.greenA2,
  green3a: greenDarkA.greenA3,
  green4a: greenDarkA.greenA4,
  green5a: greenDarkA.greenA5,
  green6a: greenDarkA.greenA6,
  green7a: greenDarkA.greenA7,
  green8a: greenDarkA.greenA8,
  green9a: greenDarkA.greenA9,
  green10a: greenDarkA.greenA10,
  green11a: greenDarkA.greenA11,
  green12a: greenDarkA.greenA12,

  grass1a: grassDarkA.grassA1,
  grass2a: grassDarkA.grassA2,
  grass3a: grassDarkA.grassA3,
  grass4a: grassDarkA.grassA4,
  grass5a: grassDarkA.grassA5,
  grass6a: grassDarkA.grassA6,
  grass7a: grassDarkA.grassA7,
  grass8a: grassDarkA.grassA8,
  grass9a: grassDarkA.grassA9,
  grass10a: grassDarkA.grassA10,
  grass11a: grassDarkA.grassA11,
  grass12a: grassDarkA.grassA12,

  lime1a: limeDarkA.limeA1,
  lime2a: limeDarkA.limeA2,
  lime3a: limeDarkA.limeA3,
  lime4a: limeDarkA.limeA4,
  lime5a: limeDarkA.limeA5,
  lime6a: limeDarkA.limeA6,
  lime7a: limeDarkA.limeA7,
  lime8a: limeDarkA.limeA8,
  lime9a: limeDarkA.limeA9,
  lime10a: limeDarkA.limeA10,
  lime11a: limeDarkA.limeA11,
  lime12a: limeDarkA.limeA12,

  mint1a: mintDarkA.mintA1,
  mint2a: mintDarkA.mintA2,
  mint3a: mintDarkA.mintA3,
  mint4a: mintDarkA.mintA4,
  mint5a: mintDarkA.mintA5,
  mint6a: mintDarkA.mintA6,
  mint7a: mintDarkA.mintA7,
  mint8a: mintDarkA.mintA8,
  mint9a: mintDarkA.mintA9,
  mint10a: mintDarkA.mintA10,
  mint11a: mintDarkA.mintA11,
  mint12a: mintDarkA.mintA12,

  sky1a: skyDarkA.skyA1,
  sky2a: skyDarkA.skyA2,
  sky3a: skyDarkA.skyA3,
  sky4a: skyDarkA.skyA4,
  sky5a: skyDarkA.skyA5,
  sky6a: skyDarkA.skyA6,
  sky7a: skyDarkA.skyA7,
  sky8a: skyDarkA.skyA8,
  sky9a: skyDarkA.skyA9,
  sky10a: skyDarkA.skyA10,
  sky11a: skyDarkA.skyA11,
  sky12a: skyDarkA.skyA12,
};

export { shared, light, dark };
