import { createConfig } from '@tokenami/config';
import * as colors from './colors';

const BASE_FONT_SIZE = 16;
const BASE_GRID_SIZE = 4;
const BP_SM = 640;
const BP_MD = 768;
const BP_LG = 1024;
const BP_XL = 1280;
const BP_2XL = 1536;

const rem = <T extends number>(value: T) => `${value / BASE_FONT_SIZE}rem` as const;
const remBreakpoint = <T extends number>(bp: T) => `@media (min-width: ${rem(bp)})` as const;

const font = <S extends string, L extends string>(fontSize: S, lineHeight: L) =>
  `var(--font-stretch) var(--font-style) var(--font-variant) var(--font-weight) ${fontSize}/${lineHeight} var(--font-family)` as const;

const optionalViaGradient = <T extends string>(direction: T) =>
  `linear-gradient(${direction}, var(--gradient-from) var(--gradient-from-stop,/**/), var(---via, var(--gradient-to) var(--gradient-to-stop,/**/)));
  ---via: var(--gradient-via) var(--gradient-via-stop,/**/), var(--gradient-to)` as const;

const fluid = <P extends string, MinPx extends number, MaxPx extends number>(params: {
  property: P;
  from: MinPx;
  to: MaxPx;
  divider?: number;
}) => {
  const divider = params.divider ?? BASE_GRID_SIZE;
  const breakpointMin = params.from / BASE_FONT_SIZE;
  const breakpointMax = params.to / BASE_FONT_SIZE;
  const breakpointScope = breakpointMax - breakpointMin;
  return `
    clamp(calc(var(---${params.property}-min) * 1rem), calc((var(---${params.property}-scope) * 100vw) + (var(---${params.property}-intercept) * 1rem)), calc(var(---${params.property}-max) * 1rem));
    ---${params.property}-min: var(--${params.property}-min) / ${divider};
    ---${params.property}-max: var(--${params.property}-max) / ${divider};
    ---${params.property}-scope: (var(---${params.property}-max) - var(---${params.property}-min)) / ${breakpointScope};
    ---${params.property}-intercept: calc(var(---${params.property}-min) - (var(---${params.property}-scope) * ${breakpointMin}));
  ` as const;
};

export default createConfig({
  include: [],
  grid: rem(BASE_GRID_SIZE),
  themeSelector: (mode) => (mode === 'root' ? ':root' : `[data-theme=${mode}]`),
  responsive: {
    sm: remBreakpoint(BP_SM),
    md: remBreakpoint(BP_MD),
    lg: remBreakpoint(BP_LG),
    xl: remBreakpoint(BP_XL),
    xxl: remBreakpoint(BP_2XL),
  },
  keyframes: {
    spin: {
      from: {
        transform: 'rotate(0deg)',
      },
      to: {
        transform: 'rotate(360deg)',
      },
    },
    ping: {
      '75%, 100%': {
        transform: 'scale(2)',
        opacity: '0',
      },
    },
    pulse: {
      '0%, 100%': {
        opacity: '1',
      },
      '50%': {
        opacity: '.5',
      },
    },
    bounce: {
      '0%, 100%': {
        transform: 'translateY(-25%)',
        animationTimingFunction: 'cubic-bezier(0.8, 0, 1, 1)',
      },
      '50%': {
        transform: 'translateY(0)',
        animationTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)',
      },
    },
    wiggle: {
      '0%, 100%': { transform: 'rotate(-3deg)' },
      '50%': { transform: 'rotate(3deg)' },
    },
  },
  // tweaked version of preflight from Tailwind https://github.com/tailwindlabs/tailwindcss/blob/next/packages/tailwindcss/preflight.css
  globalStyles: {
    ':root': {
      /* set up default vars for var(text_*) tokens */
      ['--font-family' as string]: `ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`,
      ['--font-stretch' as string]: 'normal',
      ['--font-style' as string]: 'normal',
      ['--font-variant' as string]: 'normal',
      ['--font-weight' as string]: 'normal',
    },
    '*, *::before, *::after': {
      boxSizing: 'border-box',
      margin: 0,
      padding: 0,
      border: 0,
    },
    'html, :host': {
      lineHeight: 1.5,
      WebkitTextSizeAdjust: '100%',
      tabSize: 4,
      fontFamily: 'var(--font-family)',
      fontFeatureSettings: 'normal',
      fontVariationSettings: 'normal',
      WebkitTapHighlightColor: 'transparent',
    },
    body: {
      lineHeight: 'inherit',
    },
    hr: {
      height: '0',
      color: 'inherit',
      borderTopWidth: '1px',
    },
    'abbr:where([title])': {
      textDecoration: 'underline dotted',
    },
    'h1, h2, h3, h4, h5, h6': {
      fontSize: 'inherit',
      fontWeight: 'inherit',
    },
    a: {
      color: 'inherit',
      textDecoration: 'inherit',
    },
    'b, strong': {
      fontWeight: 'bolder',
    },
    'code, kbd, samp, pre': {
      ['--font-family' as string]: `ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace`,
      fontFamily: 'var(--font-family)',
      fontFeatureSettings: 'normal',
      fontVariationSettings: 'normal',
      fontSize: '1em',
    },
    small: {
      fontSize: '80%',
    },
    'sub, sup': {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
      verticalAlign: 'baseline',
    },
    sub: {
      bottom: '-0.25em',
    },
    sup: {
      top: '-0.5em',
    },
    table: {
      textIndent: 0,
      borderColor: 'inherit',
      borderCollapse: 'collapse',
    },
    'button, input, optgroup, select, textarea, ::file-selector-button': {
      font: 'inherit',
      fontFeatureSettings: 'inherit',
      fontVariationSettings: 'inherit',
      letterSpacing: 'inherit',
      color: 'inherit',
      background: 'transparent',
    },
    'input:where(:not([type="button"], [type="reset"], [type="submit"])), select, textarea': {
      border: '1px solid',
    },
    'button, input:where([type="button"]), input:where([type="reset"]), input:where([type="submit"]), ::file-selector-button ':
      {
        appearance: 'button',
      },
    ':-moz-focusring': {
      outline: 'auto',
    },
    ':-moz-ui-invalid': {
      boxShadow: 'none',
    },
    progress: {
      verticalAlign: 'baseline',
    },
    '::-webkit-inner-spin-button, ::-webkit-outer-spin-button': {
      height: 'auto',
    },
    '::webkit-search-decoration': {
      WebkitAppearance: 'none',
    },
    summary: {
      display: 'list-item',
    },
    'ol, ul, menu': {
      listStyle: 'none',
    },
    textarea: {
      resize: 'vertical',
    },
    '::placeholder': {
      opacity: '1',
      color: 'color-mix(in srgb, currentColor 50%, transparent)',
    },
    'img, svg, video, canvas, audio, iframe, embed, object': {
      display: 'block',
      verticalAlign: 'middle',
    },
    '[hidden]:not([hidden="until-found"])': {
      display: 'none',
    },
  },
  theme: {
    modes: {
      root: {
        color: {
          current: 'currentColor',
          transparent: 'transparent',
          ...colors.shared,
          ...colors.light,
        },
      },
      light: {
        color: {
          current: 'currentColor',
          transparent: 'transparent',
          ...colors.shared,
          ...colors.light,
        },
      },
      dark: {
        color: {
          current: 'currentColor',
          transparent: 'transparent',
          ...colors.shared,
          ...colors.dark,
        },
      },
    },
    alpha: {
      '0': '0',
      '5': '0.05',
      '10': '0.1',
      '15': '0.15',
      '20': '0.2',
      '25': '0.25',
      '30': '0.3',
      '35': '0.35',
      '40': '0.4',
      '45': '0.45',
      '50': '0.5',
      '55': '0.55',
      '60': '0.6',
      '65': '0.65',
      '70': '0.7',
      '75': '0.75',
      '80': '0.8',
      '85': '0.85',
      '90': '0.9',
      '95': '0.95',
      '100': '1',
    },
    anim: {
      none: 'none',
      spin: 'spin 1s linear infinite',
      ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
      pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      bounce: 'bounce 1s infinite',
      wiggle: 'wiggle 1s ease-in-out infinite',
    },
    col: {
      auto: 'auto',
      '3xs': rem(256),
      '2xs': rem(288),
      xs: rem(320),
      sm: rem(384),
      md: rem(448),
      lg: rem(512),
      xl: rem(576),
      '2xl': rem(672),
      '3xl': rem(768),
      '4xl': rem(896),
      '5xl': rem(1024),
      '6xl': rem(1152),
      '7xl': rem(1280),
    },
    ease: {
      linear: 'linear',
      in: 'cubic-bezier(0.4, 0, 1, 1)',
      out: 'cubic-bezier(0, 0, 0.2, 1)',
      'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
    effect: {
      'alpha-0': 'opacity(0)',
      'alpha-5': 'opacity(.05)',
      'alpha-10': 'opacity(.1)',
      'alpha-15': 'opacity(.15)',
      'alpha-20': 'opacity(.2)',
      'alpha-25': 'opacity(.25)',
      'alpha-30': 'opacity(.3)',
      'alpha-35': 'opacity(.35)',
      'alpha-40': 'opacity(.4)',
      'alpha-45': 'opacity(.45)',
      'alpha-50': 'opacity(.5)',
      'alpha-55': 'opacity(.55)',
      'alpha-60': 'opacity(.6)',
      'alpha-65': 'opacity(.65)',
      'alpha-70': 'opacity(.7)',
      'alpha-75': 'opacity(.75)',
      'alpha-80': 'opacity(.8)',
      'alpha-85': 'opacity(.85)',
      'alpha-90': 'opacity(.9)',
      'alpha-95': 'opacity(.95)',
      'alpha-100': 'opacity(1)',
      'blur-none': 'blur(0)',
      'blur-sm': 'blur(4px)',
      blur: 'blur(8px)',
      'blur-md': 'blur(12px)',
      'blur-lg': 'blur(16px)',
      'blur-xl': 'blur(24px)',
      'blur-2xl': 'blur(40px)',
      'blur-3xl': 'blur(64px)',
      'bright-0': 'brightness(0)',
      'bright-50': 'brightness(.5)',
      'bright-75': 'brightness(.75)',
      'bright-90': 'brightness(.9)',
      'bright-95': 'brightness(.95)',
      'bright-100': 'brightness(1)',
      'bright-105': 'brightness(1.05)',
      'bright-110': 'brightness(1.1)',
      'bright-125': 'brightness(1.25)',
      'bright-150': 'brightness(1.5)',
      'bright-200': 'brightness(2)',
      'contrast-0': 'contrast(0)',
      'contrast-50': 'contrast(.5)',
      'contrast-75': 'contrast(.75)',
      'contrast-100': 'contrast(1)',
      'contrast-125': 'contrast(1.25)',
      'contrast-150': 'contrast(1.5)',
      'contrast-200': 'contrast(2)',
      'gray-0': 'grayscale(0)',
      'gray-100': 'grayscale(1)',
      'hue-0': 'hue-rotate(0deg)',
      'hue-15': 'hue-rotate(15deg)',
      'hue-30': 'hue-rotate(30deg)',
      'hue-60': 'hue-rotate(60deg)',
      'hue-90': 'hue-rotate(90deg)',
      'invert-0': 'invert(0)',
      'invert-100': 'invert(1)',
      'saturate-0': 'saturate(0)',
      'saturate-50': 'saturate(.5)',
      'saturate-100': 'saturate(1)',
      'saturate-150': 'saturate(1.5)',
      'saturate-200': 'saturate(2)',
      'sepia-0': 'sepia(0)',
      'sepia-100': 'sepia(1)',
    },
    flex: {
      '1': '1 1 0%',
      auto: '1 1 auto',
      initial: '0 1 auto',
      none: 'none',
    },
    'fluid-height': {
      'min-max': fluid({ property: 'fluid-height', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-height', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-height', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-height', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-height', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-height', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-height', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-height', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-height', from: BP_LG, to: BP_2XL }),
    },
    'fluid-border-spacing': {
      'min-max': fluid({ property: 'fluid-border-spacing', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-border-spacing', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-border-spacing', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-border-spacing', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-border-spacing', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-border-spacing', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-border-spacing', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-border-spacing', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-border-spacing', from: BP_LG, to: BP_2XL }),
    },
    'fluid-column-gap': {
      'min-max': fluid({ property: 'fluid-column-gap', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-column-gap', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-column-gap', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-column-gap', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-column-gap', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-column-gap', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-column-gap', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-column-gap', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-column-gap', from: BP_LG, to: BP_2XL }),
    },
    'fluid-column-width': {
      'min-max': fluid({ property: 'fluid-column-width', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-column-width', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-column-width', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-column-width', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-column-width', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-column-width', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-column-width', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-column-width', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-column-width', from: BP_LG, to: BP_2XL }),
    },
    'fluid-flex-basis': {
      'min-max': fluid({ property: 'fluid-flex-basis', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-flex-basis', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-flex-basis', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-flex-basis', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-flex-basis', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-flex-basis', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-flex-basis', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-flex-basis', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-flex-basis', from: BP_LG, to: BP_2XL }),
    },
    'fluid-text-size': {
      'min-max': fluid({ property: 'fluid-text-size', from: BP_SM, to: BP_2XL, divider: 1 }),
      'sm-md': fluid({ property: 'fluid-text-size', from: BP_SM, to: BP_MD, divider: 1 }),
      'sm-lg': fluid({ property: 'fluid-text-size', from: BP_SM, to: BP_LG, divider: 1 }),
      'sm-xl': fluid({ property: 'fluid-text-size', from: BP_SM, to: BP_XL, divider: 1 }),
      'md-lg': fluid({ property: 'fluid-text-size', from: BP_MD, to: BP_LG, divider: 1 }),
      'md-xl': fluid({ property: 'fluid-text-size', from: BP_MD, to: BP_XL, divider: 1 }),
      'md-2xl': fluid({ property: 'fluid-text-size', from: BP_MD, to: BP_2XL, divider: 1 }),
      'lg-xl': fluid({ property: 'fluid-text-size', from: BP_LG, to: BP_XL, divider: 1 }),
      'lg-2xl': fluid({ property: 'fluid-text-size', from: BP_LG, to: BP_2XL, divider: 1 }),
    },
    'fluid-gap': {
      'min-max': fluid({ property: 'fluid-gap', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-gap', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-gap', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-gap', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-gap', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-gap', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-gap', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-gap', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-gap', from: BP_LG, to: BP_2XL }),
    },
    'fluid-width': {
      'min-max': fluid({ property: 'fluid-width', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-width', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-width', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-width', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-width', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-width', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-width', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-width', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-width', from: BP_LG, to: BP_2XL }),
    },
    'fluid-inset': {
      'min-max': fluid({ property: 'fluid-inset', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-inset', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-inset', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-inset', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-inset', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-inset', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-inset', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-inset', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-inset', from: BP_LG, to: BP_2XL }),
    },
    'fluid-inset-y': {
      'min-max': fluid({ property: 'fluid-inset-y', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-inset-y', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-inset-y', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-inset-y', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-inset-y', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-inset-y', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-inset-y', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-inset-y', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-inset-y', from: BP_LG, to: BP_2XL }),
    },
    'fluid-bottom': {
      'min-max': fluid({ property: 'fluid-bottom', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-bottom', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-bottom', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-bottom', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-bottom', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-bottom', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-bottom', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-bottom', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-bottom', from: BP_LG, to: BP_2XL }),
    },
    'fluid-top': {
      'min-max': fluid({ property: 'fluid-top', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-top', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-top', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-top', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-top', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-top', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-top', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-top', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-top', from: BP_LG, to: BP_2XL }),
    },
    'fluid-inset-x': {
      'min-max': fluid({ property: 'fluid-inset-x', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-inset-x', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-inset-x', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-inset-x', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-inset-x', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-inset-x', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-inset-x', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-inset-x', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-inset-x', from: BP_LG, to: BP_2XL }),
    },
    'fluid-right': {
      'min-max': fluid({ property: 'fluid-right', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-right', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-right', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-right', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-right', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-right', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-right', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-right', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-right', from: BP_LG, to: BP_2XL }),
    },
    'fluid-left': {
      'min-max': fluid({ property: 'fluid-left', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-left', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-left', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-left', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-left', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-left', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-left', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-left', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-left', from: BP_LG, to: BP_2XL }),
    },
    'fluid-m': {
      'min-max': fluid({ property: 'fluid-m', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-m', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-m', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-m', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-m', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-m', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-m', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-m', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-m', from: BP_LG, to: BP_2XL }),
    },
    'fluid-my': {
      'min-max': fluid({ property: 'fluid-my', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-my', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-my', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-my', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-my', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-my', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-my', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-my', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-my', from: BP_LG, to: BP_2XL }),
    },
    'fluid-mb': {
      'min-max': fluid({ property: 'fluid-mb', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-mb', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-mb', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-mb', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-mb', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-mb', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-mb', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-mb', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-mb', from: BP_LG, to: BP_2XL }),
    },
    'fluid-mt': {
      'min-max': fluid({ property: 'fluid-mt', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-mt', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-mt', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-mt', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-mt', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-mt', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-mt', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-mt', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-mt', from: BP_LG, to: BP_2XL }),
    },
    'fluid-mx': {
      'min-max': fluid({ property: 'fluid-mx', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-mx', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-mx', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-mx', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-mx', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-mx', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-mx', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-mx', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-mx', from: BP_LG, to: BP_2XL }),
    },
    'fluid-mr': {
      'min-max': fluid({ property: 'fluid-mr', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-mr', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-mr', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-mr', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-mr', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-mr', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-mr', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-mr', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-mr', from: BP_LG, to: BP_2XL }),
    },
    'fluid-ml': {
      'min-max': fluid({ property: 'fluid-ml', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-ml', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-ml', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-ml', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-ml', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-ml', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-ml', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-ml', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-ml', from: BP_LG, to: BP_2XL }),
    },
    'fluid-max-height': {
      'min-max': fluid({ property: 'fluid-max-height', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-max-height', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-max-height', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-max-height', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-max-height', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-max-height', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-max-height', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-max-height', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-max-height', from: BP_LG, to: BP_2XL }),
    },
    'fluid-max-width': {
      'min-max': fluid({ property: 'fluid-max-width', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-max-width', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-max-width', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-max-width', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-max-width', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-max-width', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-max-width', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-max-width', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-max-width', from: BP_LG, to: BP_2XL }),
    },
    'fluid-min-height': {
      'min-max': fluid({ property: 'fluid-min-height', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-min-height', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-min-height', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-min-height', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-min-height', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-min-height', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-min-height', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-min-height', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-min-height', from: BP_LG, to: BP_2XL }),
    },
    'fluid-min-width': {
      'min-max': fluid({ property: 'fluid-min-width', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-min-width', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-min-width', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-min-width', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-min-width', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-min-width', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-min-width', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-min-width', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-min-width', from: BP_LG, to: BP_2XL }),
    },
    'fluid-p': {
      'min-max': fluid({ property: 'fluid-p', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-p', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-p', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-p', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-p', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-p', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-p', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-p', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-p', from: BP_LG, to: BP_2XL }),
    },
    'fluid-py': {
      'min-max': fluid({ property: 'fluid-py', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-py', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-py', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-py', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-py', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-py', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-py', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-py', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-py', from: BP_LG, to: BP_2XL }),
    },
    'fluid-pb': {
      'min-max': fluid({ property: 'fluid-pb', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-pb', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-pb', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-pb', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-pb', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-pb', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-pb', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-pb', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-pb', from: BP_LG, to: BP_2XL }),
    },
    'fluid-pt': {
      'min-max': fluid({ property: 'fluid-pt', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-pt', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-pt', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-pt', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-pt', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-pt', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-pt', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-pt', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-pt', from: BP_LG, to: BP_2XL }),
    },
    'fluid-px': {
      'min-max': fluid({ property: 'fluid-px', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-px', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-px', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-px', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-px', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-px', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-px', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-px', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-px', from: BP_LG, to: BP_2XL }),
    },
    'fluid-pr': {
      'min-max': fluid({ property: 'fluid-pr', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-pr', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-pr', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-pr', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-pr', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-pr', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-pr', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-pr', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-pr', from: BP_LG, to: BP_2XL }),
    },
    'fluid-pl': {
      'min-max': fluid({ property: 'fluid-pl', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-pl', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-pl', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-pl', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-pl', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-pl', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-pl', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-pl', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-pl', from: BP_LG, to: BP_2XL }),
    },
    'fluid-row-gap': {
      'min-max': fluid({ property: 'fluid-row-gap', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-row-gap', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-row-gap', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-row-gap', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-row-gap', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-row-gap', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-row-gap', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-row-gap', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-row-gap', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-m': {
      'min-max': fluid({ property: 'fluid-scroll-m', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-m', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-m', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-m', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-m', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-m', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-m', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-m', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-m', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-my': {
      'min-max': fluid({ property: 'fluid-scroll-my', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-my', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-my', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-my', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-my', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-my', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-my', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-my', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-my', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-mb': {
      'min-max': fluid({ property: 'fluid-scroll-mb', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-mb', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-mb', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-mb', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-mb', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-mb', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-mb', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-mb', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-mb', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-mt': {
      'min-max': fluid({ property: 'fluid-scroll-mt', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-mt', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-mt', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-mt', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-mt', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-mt', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-mt', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-mt', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-mt', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-mx': {
      'min-max': fluid({ property: 'fluid-scroll-mx', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-mx', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-mx', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-mx', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-mx', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-mx', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-mx', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-mx', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-mx', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-mr': {
      'min-max': fluid({ property: 'fluid-scroll-mr', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-mr', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-mr', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-mr', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-mr', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-mr', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-mr', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-mr', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-mr', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-ml': {
      'min-max': fluid({ property: 'fluid-scroll-ml', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-ml', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-ml', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-ml', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-ml', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-ml', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-ml', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-ml', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-ml', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-p': {
      'min-max': fluid({ property: 'fluid-scroll-p', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-p', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-p', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-p', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-p', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-p', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-p', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-p', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-p', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-py': {
      'min-max': fluid({ property: 'fluid-scroll-py', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-py', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-py', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-py', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-py', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-py', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-py', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-py', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-py', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-pb': {
      'min-max': fluid({ property: 'fluid-scroll-pb', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-pb', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-pb', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-pb', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-pb', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-pb', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-pb', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-pb', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-pb', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-pt': {
      'min-max': fluid({ property: 'fluid-scroll-pt', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-pt', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-pt', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-pt', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-pt', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-pt', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-pt', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-pt', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-pt', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-px': {
      'min-max': fluid({ property: 'fluid-scroll-px', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-px', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-px', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-px', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-px', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-px', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-px', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-px', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-px', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-pr': {
      'min-max': fluid({ property: 'fluid-scroll-pr', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-pr', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-pr', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-pr', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-pr', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-pr', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-pr', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-pr', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-pr', from: BP_LG, to: BP_2XL }),
    },
    'fluid-scroll-pl': {
      'min-max': fluid({ property: 'fluid-scroll-pl', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-scroll-pl', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-scroll-pl', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-scroll-pl', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-scroll-pl', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-scroll-pl', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-scroll-pl', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-scroll-pl', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-scroll-pl', from: BP_LG, to: BP_2XL }),
    },
    'fluid-stroke-width': {
      'min-max': fluid({ property: 'fluid-stroke-width', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-stroke-width', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-stroke-width', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-stroke-width', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-stroke-width', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-stroke-width', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-stroke-width', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-stroke-width', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-stroke-width', from: BP_LG, to: BP_2XL }),
    },
    'fluid-text-indent': {
      'min-max': fluid({ property: 'fluid-text-indent', from: BP_SM, to: BP_2XL }),
      'sm-md': fluid({ property: 'fluid-text-indent', from: BP_SM, to: BP_MD }),
      'sm-lg': fluid({ property: 'fluid-text-indent', from: BP_SM, to: BP_LG }),
      'sm-xl': fluid({ property: 'fluid-text-indent', from: BP_SM, to: BP_XL }),
      'md-lg': fluid({ property: 'fluid-text-indent', from: BP_MD, to: BP_LG }),
      'md-xl': fluid({ property: 'fluid-text-indent', from: BP_MD, to: BP_XL }),
      'md-2xl': fluid({ property: 'fluid-text-indent', from: BP_MD, to: BP_2XL }),
      'lg-xl': fluid({ property: 'fluid-text-indent', from: BP_LG, to: BP_XL }),
      'lg-2xl': fluid({ property: 'fluid-text-indent', from: BP_LG, to: BP_2XL }),
    },
    font: {
      sans: `ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`,
      serif: `ui-serif, Georgia, Cambria, "Times New Roman", Times, serif`,
      mono: `ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace`,
    },
    gradient: {
      'to-t': optionalViaGradient('to top'),
      'to-tr': optionalViaGradient('to top right'),
      'to-r': optionalViaGradient('to right'),
      'to-br': optionalViaGradient('to bottom right'),
      'to-b': optionalViaGradient('to bottom'),
      'to-bl': optionalViaGradient('to bottom left'),
      'to-l': optionalViaGradient('to left'),
      'to-tl': optionalViaGradient('to top left'),
    },
    space: {
      '0': '0',
      px: rem(1),
      auto: 'auto',
      half: '50%',
      third: '33.333333%',
      'two-thirds': '66.666667%',
      quarter: '25%',
      'three-quarters': '75%',
      full: '100%',
    },
    'grid-span': {
      '1': 'repeat(1, minmax(0, 1fr))',
      '2': 'repeat(2, minmax(0, 1fr))1',
      '3': 'repeat(3, minmax(0, 1fr))',
      '4': 'repeat(4, minmax(0, 1fr))',
      '5': 'repeat(5, minmax(0, 1fr))',
      '6': 'repeat(6, minmax(0, 1fr))',
      '7': 'repeat(7, minmax(0, 1fr))',
      '8': 'repeat(8, minmax(0, 1fr))',
      '9': 'repeat(9, minmax(0, 1fr))',
      '10': 'repeat(10, minmax(0, 1fr))',
      '11': 'repeat(11, minmax(0, 1fr))',
      '12': 'repeat(12, minmax(0, 1fr))',
      none: 'none',
      subgrid: 'subgrid',
    },
    line: {
      '0': '0 solid',
      px: `${rem(1)} solid`,
      '2': `${rem(2)} solid`,
      '4': `${rem(4)} solid`,
      '8': `${rem(8)} solid`,
    },
    'line-size': {
      '0': '0 ',
      px: rem(1),
      '2': rem(2),
      '4': rem(4),
      '8': rem(8),
    },
    leading: {
      '3': rem(12),
      '4': rem(16),
      '5': rem(20),
      '6': rem(24),
      '7': rem(28),
      '8': rem(32),
      '9': rem(36),
      '10': rem(40),
      none: '1',
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
    },
    morph: {
      none: 'none',
      all: 'all cubic-bezier(0.4, 0, 0.2, 1) 150ms',
      style: `all cubic-bezier(0.4, 0, 0.2, 1) 0ms, color 150ms, background-color 150ms, border-color 150ms, text-decoration-color 150ms, fill 150ms, stroke 150ms, opacity 150ms, box-shadow 150ms, transform 150ms, filter 150ms, backdrop-filter 150ms`,
      colors: `all cubic-bezier(0.4, 0, 0.2, 1) 0ms, color 150ms, background-color 150ms, border-color 150ms, text-decoration-color 150ms, fill 150ms, stroke 150ms`,
      opacity: `opacity cubic-bezier(0.4, 0, 0.2, 1) 150ms`,
      shadow: `box-shadow cubic-bezier(0.4, 0, 0.2, 1) 150ms`,
      transform: `transform cubic-bezier(0.4, 0, 0.2, 1) 150ms`,
    },
    offset: {
      '0': '0',
      px: rem(1),
      '2': rem(2),
      '4': rem(4),
      '8': rem(8),
    },
    radii: {
      none: '0',
      sm: rem(2),
      base: rem(4),
      md: rem(6),
      lg: rem(8),
      xl: rem(12),
      '2xl': rem(16),
      '3xl': rem(24),
      full: '9999px',
    },
    ratio: {
      auto: 'auto',
      square: '1 / 1',
      video: '16 / 9',
    },
    shadow: {
      sm: `0 1px 2px 0 var(--shadow-color, rgb(0 0 0 / 0.05))`,
      base: `0 1px 3px 0 var(--shadow-color, rgb(0 0 0 / 0.1)), 0 1px 2px -1px var(--shadow-color, rgb(0 0 0 / 0.1))`,
      md: `0 4px 6px -1px var(--shadow-color, rgb(0 0 0 / 0.1)), 0 2px 4px -2px var(--shadow-color, rgb(0 0 0 / 0.1))`,
      lg: `0 10px 15px -3px var(--shadow-color, rgb(0 0 0 / 0.1)), 0 4px 6px -4px var(--shadow-color, rgb(0 0 0 / 0.1))`,
      xl: `0 20px 25px -5px var(--shadow-color, rgb(0 0 0 / 0.1)), 0 10px 10px -5px var(--shadow-color, rgb(0 0 0 / 0.1))`,
      '2xl': `0 25px 50px -12px var(--shadow-color, rgb(0 0 0 / 0.25))`,
      inner: `inset 0 2px 4px 0 var(--shadow-color, rgb(0 0 0 / 0.05))`,
      none: 'none',
    },
    size: {
      '0': '0',
      px: rem(1),
      auto: 'auto',
      fit: 'fit-content',
      full: '100%',
      half: '50%',
      third: '33.333333%',
      'two-thirds': '66.666667%',
      quarter: '25%',
      'three-quarters': '75%',
      min: 'min-content',
      max: 'max-content',
      'screen-w': '100vw',
      'screen-h': '100vh',
      dvh: '100dvh',
      dvw: '100dvw',
      svh: '100svh',
      svw: '100svw',
      lvh: '100lvh',
      lvw: '100lvw',
    },
    span: {
      auto: 'auto',
      'span-1': 'span 1 / span 1',
      'span-2': 'span 2 / span 2',
      'span-3': 'span 3 / span 3',
      'span-4': 'span 4 / span 4',
      'span-5': 'span 5 / span 5',
      'span-6': 'span 6 / span 6',
      'span-7': 'span 7 / span 7',
      'span-8': 'span 8 / span 8',
      'span-9': 'span 9 / span 9',
      'span-10': 'span 10 / span 10',
      'span-11': 'span 11 / span 11',
      'span-12': 'span 12 / span 12',
      'span-full': '1 / -1',
    },
    stop: {
      '0': '0%',
      '5': '5%',
      '10': '10%',
      '15': '15%',
      '20': '20%',
      '25': '25%',
      '30': '30%',
      '35': '35%',
      '40': '40%',
      '45': '45%',
      '50': '50%',
      '55': '55%',
      '60': '60%',
      '65': '65%',
      '70': '70%',
      '75': '75%',
      '80': '80%',
      '85': '85%',
      '90': '90%',
      '95': '95%',
      '100': '100%',
    },
    time: {
      '0': '0ms',
      '75': '75ms',
      '100': '100ms',
      '150': '150ms',
      '200': '200ms',
      '300': '300ms',
      '500': '500ms',
      '700': '700ms',
      '1000': '1000ms',
    },
    text: {
      xs: font(rem(12), rem(16)),
      sm: font(rem(14), rem(20)),
      base: font(rem(16), rem(24)),
      lg: font(rem(18), rem(28)),
      xl: font(rem(20), rem(28)),
      '2xl': font(rem(24), rem(32)),
      '3xl': font(rem(30), rem(36)),
      '4xl': font(rem(36), rem(40)),
      '5xl': font(rem(48), '1'),
      '6xl': font(rem(60), '1'),
      '7xl': font(rem(72), '1'),
      '8xl': font(rem(96), '1'),
      '9xl': font(rem(128), '1'),
    },
    'text-size': {
      xs: rem(12),
      sm: rem(14),
      base: rem(16),
      lg: rem(18),
      xl: rem(20),
      '2xl': rem(24),
      '3xl': rem(30),
      '4xl': rem(36),
      '5xl': rem(48),
      '6xl': rem(60),
      '7xl': rem(72),
      '8xl': rem(96),
      '9xl': rem(128),
    },
    tracking: {
      tighter: '-0.05em',
      tight: '-0.025em',
      normal: '0',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
    },
    weight: {
      thin: '100',
      extralight: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900',
    },
  },
  selectors: {
    'prefers-dark': ['@media (prefers-color-scheme: dark)', '&'],
    'prefers-light': ['@media (prefers-color-scheme: light)', '&'],
    portrait: ['@media (orientation: portrait)', '&'],
    landscape: ['@media (orientation: landscape)', '&'],
    'motion-safe': ['@media (prefers-reduced-motion: no-preference)', '&'],
    'motion-reduce': ['@media (prefers-reduced-motion: reduce)', '&'],
    'contrast-more': ['@media (contrast: more)', '&'],
    'contrast-less': ['@media (contrast: less)', '&'],
    print: ['@media print', '&'],
    hover: ['@media (hover: hover) and (pointer: fine)', '&:not(:disabled):hover'],
    focus: ['&:not(:disabled):focus'],
    'focus-within': '&:focus-within',
    'focus-visible': '&:focus-visible',
    active: '&:active',
    visited: '&:visited',
    target: '&:target',
    first: '&:first-child',
    last: '&:last-child',
    only: '&:only-child',
    odd: '&:nth-child(odd)',
    even: '&:nth-child(even)',
    child: '& > *',
    'first-of-type': '&:first-of-type',
    'last-of-type': '&:last-of-type',
    'only-of-type': '&:only-of-type',
    empty: '&:empty',
    disabled: '&:disabled',
    enabled: '&:enabled',
    checked: '&:checked',
    indeterminate: '&:indeterminate',
    default: '&:default',
    optional: '&:optional',
    required: '&:required',
    valid: '&:valid',
    invalid: '&:invalid',
    'in-range': '&:in-range',
    'out-of-range': '&:out-of-range',
    'placeholder-shown': '&:placeholder-shown',
    autofill: '&:autofill',
    'read-only': '&:read-only',
    flow: '& > * + *',
    dark: '[data-theme=dark] &',
    light: '[data-theme=light] &',
    rtl: '[dir=rtl] &',
    ltr: '[dir=ltr] &',
    open: '&[open]',
    after: '&::after',
    before: '&::before',
    'first-letter': '&::first-letter',
    'first-line': '&::first-line',
    marker: '&::marker',
    selection: '&::selection',
    file: '&::file-selector-button',
    backdrop: '&::backdrop',
    placeholder: '&::placeholder',
    'aria-busy': '&[aria-busy=true]',
    'aria-checked': '&[aria-checked=true]',
    'aria-disabled': '&[aria-disabled=true]',
    'aria-expanded': '&[aria-expanded=true]',
    'aria-hidden': '&[aria-hidden=true]',
    'aria-pressed': '&[aria-pressed=true]',
    'aria-readonly': '&[aria-readonly=true]',
    'aria-required': '&[aria-required=true]',
    'aria-selected': '&[aria-selected=true]',
  },
  aliases: {
    bg: ['background-color'],
    'bg-gradient': ['background-image'],
    'bg-position': ['background-position'],
    'bg-size': ['background-size'],
    bottom: ['inset-block-end'],
    'border-top': ['border-block-start'],
    'border-right': ['border-inline-end'],
    'border-bottom': ['border-block-end'],
    'border-left': ['border-inline-start'],
    'border-top-width': ['border-block-start-width'],
    'border-right-width': ['border-inline-end-width'],
    'border-bottom-width': ['border-block-end-width'],
    'border-left-width': ['border-inline-start-width'],
    'border-x': ['border-inline'],
    'border-y': ['border-block'],
    'border-top-left-radius': ['border-start-start-radius'],
    'border-top-right-radius': ['border-start-end-radius'],
    'border-bottom-left-radius': ['border-end-start-radius'],
    'border-bottom-right-radius': ['border-end-end-radius'],
    'radius-left': ['border-start-start-radius', 'border-end-start-radius'],
    'radius-right': ['border-start-end-radius', 'border-end-end-radius'],
    'radius-top': ['border-start-start-radius', 'border-start-end-radius'],
    'radius-bottom': ['border-end-start-radius', 'border-end-end-radius'],
    'radius-top-left': ['border-start-start-radius'],
    'radius-top-right': ['border-start-end-radius'],
    'radius-bottom-left': ['border-end-start-radius'],
    'radius-bottom-right': ['border-end-end-radius'],
    'gap-x': ['column-gap'],
    'gap-y': ['row-gap'],
    height: ['block-size'],
    h: ['block-size'],
    'inset-x': ['inset-inline'],
    'inset-y': ['inset-block'],
    left: ['inset-inline-start'],
    'margin-top': ['margin-block-start'],
    'margin-right': ['margin-inline-end'],
    'margin-bottom': ['margin-block-end'],
    'margin-left': ['margin-inline-start'],
    m: ['margin'],
    mt: ['margin-block-start'],
    mr: ['margin-inline-end'],
    mb: ['margin-block-end'],
    ml: ['margin-inline-start'],
    mx: ['margin-inline'],
    my: ['margin-block'],
    'padding-top': ['padding-block-start'],
    'padding-right': ['padding-inline-end'],
    'padding-bottom': ['padding-block-end'],
    'padding-left': ['padding-inline-start'],
    p: ['padding'],
    pt: ['padding-block-start'],
    pr: ['padding-inline-end'],
    pb: ['padding-block-end'],
    pl: ['padding-inline-start'],
    px: ['padding-inline'],
    py: ['padding-block'],
    right: ['inset-inline-end'],
    'scroll-margin-top': ['scroll-margin-block-start'],
    'scroll-margin-right': ['scroll-margin-inline-end'],
    'scroll-margin-bottom': ['scroll-margin-block-end'],
    'scroll-margin-left': ['scroll-margin-inline-start'],
    'scroll-m': ['scroll-margin'],
    'scroll-mt': ['scroll-margin-block-start'],
    'scroll-mr': ['scroll-margin-inline-end'],
    'scroll-mb': ['scroll-margin-block-end'],
    'scroll-ml': ['scroll-margin-inline-start'],
    'scroll-mx': ['scroll-margin-inline'],
    'scroll-my': ['scroll-margin-block'],
    'scroll-padding-top': ['scroll-padding-block-start'],
    'scroll-padding-right': ['scroll-padding-inline-end'],
    'scroll-padding-bottom': ['scroll-padding-block-end'],
    'scroll-padding-left': ['scroll-padding-inline-start'],
    'scroll-p': ['scroll-padding'],
    'scroll-pt': ['scroll-padding-block-start'],
    'scroll-pr': ['scroll-padding-inline-end'],
    'scroll-pb': ['scroll-padding-block-end'],
    'scroll-pl': ['scroll-padding-inline-start'],
    'scroll-px': ['scroll-padding-inline'],
    'scroll-py': ['scroll-padding-block'],
    size: ['block-size', 'inline-size'],
    top: ['inset-block-start'],
    width: ['inline-size'],
    w: ['inline-size'],
  },
  properties: {
    'accent-color': ['color'],
    animation: ['anim'],
    'animation-timing-function': ['ease'],
    'aspect-ratio': ['ratio'],
    'backdrop-filter': ['effect'],
    background: ['color', 'gradient'],
    'background-color': ['color'],
    'background-image': ['gradient'],
    'background-position-x': ['grid', 'space'],
    'background-position-y': ['grid', 'space'],
    'block-size': ['size', 'grid', 'fluid-height'],
    'block-size-min': ['number'],
    'block-size-max': ['number'],
    border: ['line'],
    'border-top': ['line'],
    'border-right': ['line'],
    'border-bottom': ['line'],
    'border-left': ['line'],
    'border-width': ['line-size'],
    'border-top-width': ['line-size'],
    'border-right-width': ['line-size'],
    'border-bottom-width': ['line-size'],
    'border-left-width': ['line-size'],
    'border-block': ['line'],
    'border-block-start': ['line'],
    'border-block-start-width': ['line-size'],
    'border-block-end': ['line'],
    'border-block-end-width': ['line-size'],
    'border-inline': ['line'],
    'border-inline-start': ['line'],
    'border-inline-start-width': ['line-size'],
    'border-inline-end': ['line'],
    'border-inline-end-width': ['line-size'],
    'border-color': ['color'],
    'border-top-color': ['color'],
    'border-right-color': ['color'],
    'border-bottom-color': ['color'],
    'border-left-color': ['color'],
    'border-block-color': ['color'],
    'border-block-start-color': ['color'],
    'border-block-end-color': ['color'],
    'border-inline-color': ['color'],
    'border-inline-start-color': ['color'],
    'border-inline-end-color': ['color'],
    'border-radius': ['radii'],
    'border-top-left-radius': ['radii'],
    'border-top-right-radius': ['radii'],
    'border-bottom-left-radius': ['radii'],
    'border-bottom-right-radius': ['radii'],
    'border-start-end-radius': ['radii'],
    'border-start-start-radius': ['radii'],
    'border-end-start-radius': ['radii'],
    'border-end-end-radius': ['radii'],
    'border-spacing': ['grid', 'fluid-border-spacing'],
    bottom: ['grid', 'space', 'fluid-bottom'],
    'box-shadow': ['shadow'],
    'caret-color': ['color'],
    color: ['color'],
    'column-gap': ['grid', 'fluid-column-gap'],
    'column-rule': ['line'],
    'column-rule-color': ['color'],
    'column-rule-width': ['line-size'],
    columns: ['col'],
    'column-width': ['size', 'grid', 'fluid-column-width'],
    filter: ['effect', 'drop-shadow'],
    fill: ['color'],
    flex: ['flex'],
    'flex-basis': ['grid', 'space', 'fluid-flex-basis'],
    'flex-basis-min': ['number'],
    'flex-basis-max': ['number'],
    'fluid-height-min': ['number'],
    'fluid-height-max': ['number'],
    'fluid-border-spacing-min': ['number'],
    'fluid-border-spacing-max': ['number'],
    'fluid-column-gap-min': ['number'],
    'fluid-column-gap-max': ['number'],
    'fluid-column-width-min': ['number'],
    'fluid-column-width-max': ['number'],
    'fluid-flex-basis-min': ['number'],
    'fluid-flex-basis-max': ['number'],
    'fluid-text-size-min': ['number'],
    'fluid-text-size-max': ['number'],
    'fluid-gap-min': ['number'],
    'fluid-gap-max': ['number'],
    'fluid-width-min': ['number'],
    'fluid-width-max': ['number'],
    'fluid-inset-min': ['number'],
    'fluid-inset-max': ['number'],
    'fluid-inset-y-min': ['number'],
    'fluid-inset-y-max': ['number'],
    'fluid-bottom-min': ['number'],
    'fluid-bottom-max': ['number'],
    'fluid-top-min': ['number'],
    'fluid-top-max': ['number'],
    'fluid-inset-x-min': ['number'],
    'fluid-inset-x-max': ['number'],
    'fluid-right-min': ['number'],
    'fluid-right-max': ['number'],
    'fluid-left-min': ['number'],
    'fluid-left-max': ['number'],
    'fluid-m-min': ['number'],
    'fluid-m-max': ['number'],
    'fluid-my-min': ['number'],
    'fluid-my-max': ['number'],
    'fluid-mb-min': ['number'],
    'fluid-mb-max': ['number'],
    'fluid-mt-min': ['number'],
    'fluid-mt-max': ['number'],
    'fluid-mx-min': ['number'],
    'fluid-mx-max': ['number'],
    'fluid-mr-min': ['number'],
    'fluid-mr-max': ['number'],
    'fluid-ml-min': ['number'],
    'fluid-ml-max': ['number'],
    'fluid-max-height-min': ['number'],
    'fluid-max-height-max': ['number'],
    'fluid-max-width-min': ['number'],
    'fluid-max-width-max': ['number'],
    'fluid-min-height-min': ['number'],
    'fluid-min-height-max': ['number'],
    'fluid-min-width-min': ['number'],
    'fluid-min-width-max': ['number'],
    'fluid-p-min': ['number'],
    'fluid-p-max': ['number'],
    'fluid-py-min': ['number'],
    'fluid-py-max': ['number'],
    'fluid-pb-min': ['number'],
    'fluid-pb-max': ['number'],
    'fluid-pt-min': ['number'],
    'fluid-pt-max': ['number'],
    'fluid-px-min': ['number'],
    'fluid-px-max': ['number'],
    'fluid-pr-min': ['number'],
    'fluid-pr-max': ['number'],
    'fluid-pl-min': ['number'],
    'fluid-pl-max': ['number'],
    'fluid-row-gap-min': ['number'],
    'fluid-row-gap-max': ['number'],
    'fluid-scroll-m-min': ['number'],
    'fluid-scroll-m-max': ['number'],
    'fluid-scroll-my-min': ['number'],
    'fluid-scroll-my-max': ['number'],
    'fluid-scroll-mb-min': ['number'],
    'fluid-scroll-mb-max': ['number'],
    'fluid-scroll-mt-min': ['number'],
    'fluid-scroll-mt-max': ['number'],
    'fluid-scroll-mx-min': ['number'],
    'fluid-scroll-mx-max': ['number'],
    'fluid-scroll-mr-min': ['number'],
    'fluid-scroll-mr-max': ['number'],
    'fluid-scroll-ml-min': ['number'],
    'fluid-scroll-ml-max': ['number'],
    'fluid-scroll-p-min': ['number'],
    'fluid-scroll-p-max': ['number'],
    'fluid-scroll-py-min': ['number'],
    'fluid-scroll-py-max': ['number'],
    'fluid-scroll-pb-min': ['number'],
    'fluid-scroll-pb-max': ['number'],
    'fluid-scroll-pt-min': ['number'],
    'fluid-scroll-pt-max': ['number'],
    'fluid-scroll-px-min': ['number'],
    'fluid-scroll-px-max': ['number'],
    'fluid-scroll-pr-min': ['number'],
    'fluid-scroll-pr-max': ['number'],
    'fluid-scroll-pl-min': ['number'],
    'fluid-scroll-pl-max': ['number'],
    'fluid-stroke-width-min': ['number'],
    'fluid-stroke-width-max': ['number'],
    'fluid-text-indent-min': ['number'],
    'fluid-text-indent-max': ['number'],
    font: ['text'],
    'font-family': ['font'],
    'font-size': ['text-size', 'fluid-text-size'],
    'font-weight': ['weight'],
    'line-height': ['leading'],
    gap: ['grid', 'fluid-gap'],
    'gradient-from': ['color'],
    'gradient-from-stop': ['stop'],
    'gradient-to': ['color'],
    'gradient-to-stop': ['stop'],
    'gradient-via': ['color'],
    'gradient-via-stop': ['stop'],
    'grid-column': ['span'],
    'grid-row': ['span'],
    'grid-template-rows': ['grid-span'],
    'grid-template-columns': ['grid-span'],
    height: ['size', 'grid', 'fluid-height'],
    'inline-size': ['size', 'grid', 'fluid-width'],
    inset: ['grid', 'space', 'fluid-inset'],
    'inset-block': ['grid', 'space', 'fluid-inset-y'],
    'inset-block-end': ['grid', 'space', 'fluid-bottom'],
    'inset-block-start': ['grid', 'space', 'fluid-top'],
    'inset-inline': ['grid', 'space', 'fluid-inset-x'],
    'inset-inline-end': ['grid', 'space', 'fluid-right'],
    'inset-inline-start': ['grid', 'space', 'fluid-left'],
    left: ['grid', 'space', 'fluid-left'],
    'letter-spacing': ['tracking'],
    margin: ['grid', 'fluid-m'],
    'margin-block': ['grid', 'fluid-my'],
    'margin-block-end': ['grid', 'fluid-mb'],
    'margin-block-start': ['grid', 'fluid-mt'],
    'margin-inline': ['grid', 'fluid-mx'],
    'margin-inline-end': ['grid', 'fluid-mr'],
    'margin-inline-start': ['grid', 'fluid-ml'],
    'margin-top': ['grid', 'fluid-mt'],
    'margin-right': ['grid', 'fluid-mr'],
    'margin-bottom': ['grid', 'fluid-mb'],
    'margin-left': ['grid', 'fluid-ml'],
    'max-block-size': ['size', 'grid', 'fluid-max-height'],
    'max-height': ['size', 'grid', 'fluid-max-width'],
    'max-inline-size': ['size', 'grid', 'fluid-max-width'],
    'max-width': ['size', 'grid', 'fluid-max-height'],
    'min-block-size': ['size', 'grid', 'fluid-min-height'],
    'min-height': ['size', 'grid', 'fluid-min-width'],
    'min-inline-size': ['size', 'grid', 'fluid-min-width'],
    'min-width': ['size', 'grid', 'fluid-min-height'],
    opacity: ['alpha'],
    outline: ['line'],
    'outline-color': ['color'],
    'outline-width': ['line-size'],
    'outline-offset': ['offset'],
    padding: ['grid', 'fluid-p'],
    'padding-block': ['grid', 'fluid-py'],
    'padding-block-end': ['grid', 'fluid-pb'],
    'padding-block-start': ['grid', 'fluid-pt'],
    'padding-inline': ['grid', 'fluid-px'],
    'padding-inline-end': ['grid', 'fluid-pr'],
    'padding-inline-start': ['grid', 'fluid-pl'],
    'padding-top': ['grid', 'fluid-pt'],
    'padding-right': ['grid', 'fluid-pr'],
    'padding-bottom': ['grid', 'fluid-pb'],
    'padding-left': ['grid', 'fluid-pl'],
    right: ['grid', 'space', 'fluid-right'],
    'row-gap': ['grid', 'fluid-row-gap'],
    'scroll-margin': ['grid', 'fluid-scroll-m'],
    'scroll-margin-block': ['grid', 'fluid-scroll-my'],
    'scroll-margin-block-end': ['grid', 'fluid-scroll-mb'],
    'scroll-margin-block-start': ['grid', 'fluid-scroll-mt'],
    'scroll-margin-inline': ['grid', 'fluid-scroll-mx'],
    'scroll-margin-inline-end': ['grid', 'fluid-scroll-mr'],
    'scroll-margin-inline-start': ['grid', 'fluid-scroll-ml'],
    'scroll-margin-top': ['grid', 'fluid-scroll-mt'],
    'scroll-margin-right': ['grid', 'fluid-scroll-mr'],
    'scroll-margin-bottom': ['grid', 'fluid-scroll-mb'],
    'scroll-margin-left': ['grid', 'fluid-scroll-ml'],
    'scroll-padding': ['grid', 'fluid-scroll-p'],
    'scroll-padding-block': ['grid', 'fluid-scroll-py'],
    'scroll-padding-block-end': ['grid', 'fluid-scroll-pb'],
    'scroll-padding-block-start': ['grid', 'fluid-scroll-pt'],
    'scroll-padding-inline': ['grid', 'fluid-scroll-px'],
    'scroll-padding-inline-end': ['grid', 'fluid-scroll-pr'],
    'scroll-padding-inline-start': ['grid', 'fluid-scroll-pl'],
    'scroll-padding-top': ['grid', 'fluid-scroll-pt'],
    'scroll-padding-right': ['grid', 'fluid-scroll-pr'],
    'scroll-padding-bottom': ['grid', 'fluid-scroll-pb'],
    'scroll-padding-left': ['grid', 'fluid-scroll-pl'],
    'shadow-color': ['color'],
    stroke: ['color'],
    'stroke-width': ['grid', 'fluid-stroke-width'],
    'text-decoration-color': ['color'],
    'text-indent': ['grid', 'fluid-text-indent'],
    'text-shadow': ['shadow'],
    top: ['grid', 'space', 'fluid-top'],
    transition: ['morph'],
    'transition-duration': ['time'],
    'transition-timing-function': ['ease'],
    'transition-delay': ['time'],
    width: ['size', 'grid', 'fluid-width'],
  },
});
