import type * as CSS from 'csstype';
import type { Theme } from '~/theme';

type PropertyConfig = { themeKey: keyof Theme | 'unknown'; initial?: string };

const themeConfig = {
  '-webkit-line-clamp': { themeKey: 'unknown', initial: '' },
  'accent-color': { themeKey: 'unknown', initial: '' },
  'align-content': { themeKey: 'unknown', initial: '' },
  'align-items': { themeKey: 'unknown', initial: '' },
  'align-self': { themeKey: 'unknown', initial: '' },
  'align-tracks': { themeKey: 'unknown', initial: '' },
  all: { themeKey: 'unknown', initial: '' },
  animation: { themeKey: 'unknown', initial: '' },
  'animation-composition': { themeKey: 'unknown', initial: '' },
  'animation-delay': { themeKey: 'unknown', initial: '' },
  'animation-direction': { themeKey: 'unknown', initial: '' },
  'animation-duration': { themeKey: 'unknown', initial: '' },
  'animation-fill-mode': { themeKey: 'unknown', initial: '' },
  'animation-iteration-count': { themeKey: 'unknown', initial: '' },
  'animation-name': { themeKey: 'unknown', initial: '' },
  'animation-play-state': { themeKey: 'unknown', initial: '' },
  'animation-timeline': { themeKey: 'unknown', initial: '' },
  'animation-timing-function': { themeKey: 'unknown', initial: '' },
  appearance: { themeKey: 'unknown', initial: '' },
  'aspect-ratio': { themeKey: 'unknown', initial: '' },
  'backdrop-filter': { themeKey: 'unknown', initial: '' },
  'backface-visibility': { themeKey: 'unknown', initial: '' },
  background: { themeKey: 'colors', initial: '' },
  'background-attachment': { themeKey: 'unknown', initial: '' },
  'background-blend-mode': { themeKey: 'unknown', initial: '' },
  'background-clip': { themeKey: 'unknown', initial: '' },
  'background-color': { themeKey: 'colors', initial: '' },
  'background-image': { themeKey: 'unknown', initial: '' },
  'background-origin': { themeKey: 'unknown', initial: '' },
  'background-position': { themeKey: 'grid', initial: '' },
  'background-position-x': { themeKey: 'grid', initial: '' },
  'background-position-y': { themeKey: 'grid', initial: '' },
  'background-repeat': { themeKey: 'unknown', initial: '' },
  'background-size': { themeKey: 'unknown', initial: '' },
  'block-overflow': { themeKey: 'unknown', initial: '' },
  'block-size': { themeKey: 'sizes', initial: '' },
  border: { themeKey: 'borders', initial: '' },
  'border-block': { themeKey: 'borders', initial: '' },
  'border-block-color': { themeKey: 'colors', initial: '' },
  'border-block-end': { themeKey: 'borders', initial: '' },
  'border-block-end-color': { themeKey: 'colors', initial: '' },
  'border-block-end-style': { themeKey: 'borderStyles', initial: '' },
  'border-block-end-width': { themeKey: 'borderWidths', initial: '' },
  'border-block-start': { themeKey: 'borders', initial: '' },
  'border-block-start-color': { themeKey: 'colors', initial: '' },
  'border-block-start-style': { themeKey: 'borderStyles', initial: '' },
  'border-block-start-width': { themeKey: 'borderWidths', initial: '' },
  'border-block-style': { themeKey: 'borderStyles', initial: '' },
  'border-block-width': { themeKey: 'borderWidths', initial: '' },
  'border-bottom': { themeKey: 'borders', initial: '' },
  'border-bottom-color': { themeKey: 'colors', initial: '' },
  'border-bottom-left-radius': { themeKey: 'radii', initial: '' },
  'border-bottom-right-radius': { themeKey: 'radii', initial: '' },
  'border-bottom-style': { themeKey: 'borderStyles', initial: '' },
  'border-bottom-width': { themeKey: 'borderWidths', initial: '' },
  'border-collapse': { themeKey: 'unknown', initial: '' },
  'border-color': { themeKey: 'colors', initial: '' },
  'border-end-end-radius': { themeKey: 'radii', initial: '' },
  'border-end-start-radius': { themeKey: 'radii', initial: '' },
  'border-image': { themeKey: 'unknown', initial: '' },
  'border-image-outset': { themeKey: 'unknown', initial: '' },
  'border-image-repeat': { themeKey: 'unknown', initial: '' },
  'border-image-slice': { themeKey: 'unknown', initial: '' },
  'border-image-source': { themeKey: 'unknown', initial: '' },
  'border-image-width': { themeKey: 'unknown', initial: '' },
  'border-inline': { themeKey: 'borders', initial: '' },
  'border-inline-color': { themeKey: 'colors', initial: '' },
  'border-inline-end': { themeKey: 'borders', initial: '' },
  'border-inline-end-color': { themeKey: 'colors', initial: '' },
  'border-inline-end-style': { themeKey: 'borderStyles', initial: '' },
  'border-inline-end-width': { themeKey: 'borderWidths', initial: '' },
  'border-inline-start': { themeKey: 'borders', initial: '' },
  'border-inline-start-color': { themeKey: 'colors', initial: '' },
  'border-inline-start-style': { themeKey: 'borderStyles', initial: '' },
  'border-inline-start-width': { themeKey: 'borderWidths', initial: '' },
  'border-inline-style': { themeKey: 'borderStyles', initial: '' },
  'border-inline-width': { themeKey: 'borderWidths', initial: '' },
  'border-left': { themeKey: 'borders', initial: '' },
  'border-left-color': { themeKey: 'colors', initial: '' },
  'border-left-style': { themeKey: 'borderStyles', initial: '' },
  'border-left-width': { themeKey: 'borderWidths', initial: '' },
  'border-radius': { themeKey: 'radii', initial: '' },
  'border-right': { themeKey: 'borders', initial: '' },
  'border-right-color': { themeKey: 'colors', initial: '' },
  'border-right-style': { themeKey: 'borderStyles', initial: '' },
  'border-right-width': { themeKey: 'borderWidths', initial: '' },
  'border-spacing': { themeKey: 'unknown', initial: '' },
  'border-start-end-radius': { themeKey: 'radii', initial: '' },
  'border-start-start-radius': { themeKey: 'radii', initial: '' },
  'border-style': { themeKey: 'borderStyles', initial: '' },
  'border-top': { themeKey: 'borders', initial: '' },
  'border-top-color': { themeKey: 'colors', initial: '' },
  'border-top-left-radius': { themeKey: 'radii', initial: '' },
  'border-top-right-radius': { themeKey: 'radii', initial: '' },
  'border-top-style': { themeKey: 'borderStyles', initial: '' },
  'border-top-width': { themeKey: 'borderWidths', initial: '' },
  'border-width': { themeKey: 'borderWidths', initial: '' },
  bottom: { themeKey: 'grid', initial: '0' },
  'box-decoration-break': { themeKey: 'unknown', initial: '' },
  'box-shadow': { themeKey: 'shadows', initial: '' },
  'box-sizing': { themeKey: 'unknown', initial: '' },
  'break-after': { themeKey: 'unknown', initial: '' },
  'break-before': { themeKey: 'unknown', initial: '' },
  'break-inside': { themeKey: 'unknown', initial: '' },
  'caption-side': { themeKey: 'unknown', initial: '' },
  caret: { themeKey: 'unknown', initial: '' },
  'caret-color': { themeKey: 'colors', initial: '' },
  'caret-shape': { themeKey: 'unknown', initial: '' },
  clear: { themeKey: 'unknown', initial: '' },
  clip: { themeKey: 'unknown', initial: '' },
  'clip-path': { themeKey: 'unknown', initial: '' },
  color: { themeKey: 'colors', initial: '' },
  'color-scheme': { themeKey: 'unknown', initial: '' },
  'column-count': { themeKey: 'unknown', initial: '' },
  'column-fill': { themeKey: 'unknown', initial: '' },
  'column-gap': { themeKey: 'grid', initial: '0' },
  'column-rule': { themeKey: 'unknown', initial: '' },
  'column-rule-color': { themeKey: 'colors', initial: '' },
  'column-rule-style': { themeKey: 'unknown', initial: '' },
  'column-rule-width': { themeKey: 'borderWidths', initial: '' },
  'column-span': { themeKey: 'unknown', initial: '' },
  'column-width': { themeKey: 'sizes', initial: '' },
  columns: { themeKey: 'unknown', initial: '' },
  contain: { themeKey: 'unknown', initial: '' },
  'contain-intrinsic-block-size': { themeKey: 'unknown', initial: '' },
  'contain-intrinsic-height': { themeKey: 'unknown', initial: '' },
  'contain-intrinsic-inline-size': { themeKey: 'unknown', initial: '' },
  'contain-intrinsic-size': { themeKey: 'unknown', initial: '' },
  'contain-intrinsic-width': { themeKey: 'unknown', initial: '' },
  container: { themeKey: 'unknown', initial: '' },
  'container-name': { themeKey: 'unknown', initial: '' },
  'container-type': { themeKey: 'unknown', initial: '' },
  content: { themeKey: 'unknown', initial: '' },
  'content-visibility': { themeKey: 'unknown', initial: '' },
  'counter-increment': { themeKey: 'unknown', initial: '' },
  'counter-reset': { themeKey: 'unknown', initial: '' },
  'counter-set': { themeKey: 'unknown', initial: '' },
  cursor: { themeKey: 'unknown', initial: '' },
  direction: { themeKey: 'unknown', initial: '' },
  display: { themeKey: 'unknown', initial: '' },
  'empty-cells': { themeKey: 'unknown', initial: '' },
  filter: { themeKey: 'unknown', initial: '' },
  flex: { themeKey: 'unknown', initial: '' },
  'flex-basis': { themeKey: 'sizes', initial: '' },
  'flex-direction': { themeKey: 'unknown', initial: '' },
  'flex-flow': { themeKey: 'unknown', initial: '' },
  'flex-grow': { themeKey: 'unknown', initial: '' },
  'flex-shrink': { themeKey: 'unknown', initial: '' },
  'flex-wrap': { themeKey: 'unknown', initial: '' },
  float: { themeKey: 'unknown', initial: '' },
  font: { themeKey: 'unknown', initial: '' },
  'font-family': { themeKey: 'fonts', initial: '' },
  'font-feature-settings': { themeKey: 'unknown', initial: '' },
  'font-kerning': { themeKey: 'unknown', initial: '' },
  'font-language-override': { themeKey: 'unknown', initial: '' },
  'font-optical-sizing': { themeKey: 'unknown', initial: '' },
  'font-palette': { themeKey: 'unknown', initial: '' },
  'font-size': { themeKey: 'fontSizes', initial: '' },
  'font-size-adjust': { themeKey: 'unknown', initial: '' },
  'font-stretch': { themeKey: 'unknown', initial: '' },
  'font-style': { themeKey: 'unknown', initial: '' },
  'font-synthesis': { themeKey: 'unknown', initial: '' },
  'font-variant': { themeKey: 'unknown', initial: '' },
  'font-variant-alternates': { themeKey: 'unknown', initial: '' },
  'font-variant-caps': { themeKey: 'unknown', initial: '' },
  'font-variant-east-asian': { themeKey: 'unknown', initial: '' },
  'font-variant-emoji': { themeKey: 'unknown', initial: '' },
  'font-variant-ligatures': { themeKey: 'unknown', initial: '' },
  'font-variant-numeric': { themeKey: 'unknown', initial: '' },
  'font-variant-position': { themeKey: 'unknown', initial: '' },
  'font-variation-settings': { themeKey: 'unknown', initial: '' },
  'font-weight': { themeKey: 'fontWeights', initial: '' },
  'forced-color-adjust': { themeKey: 'unknown', initial: '' },
  gap: { themeKey: 'grid', initial: '0' },
  grid: { themeKey: 'unknown', initial: '' },
  'grid-area': { themeKey: 'unknown', initial: '' },
  'grid-auto-columns': { themeKey: 'unknown', initial: '' },
  'grid-auto-flow': { themeKey: 'unknown', initial: '' },
  'grid-auto-rows': { themeKey: 'unknown', initial: '' },
  'grid-column': { themeKey: 'unknown', initial: '' },
  'grid-column-end': { themeKey: 'unknown', initial: '' },
  'grid-column-start': { themeKey: 'unknown', initial: '' },
  'grid-row': { themeKey: 'unknown', initial: '' },
  'grid-row-end': { themeKey: 'unknown', initial: '' },
  'grid-row-start': { themeKey: 'unknown', initial: '' },
  'grid-template': { themeKey: 'unknown', initial: '' },
  'grid-template-areas': { themeKey: 'unknown', initial: '' },
  'grid-template-columns': { themeKey: 'unknown', initial: '' },
  'grid-template-rows': { themeKey: 'unknown', initial: '' },
  'hanging-punctuation': { themeKey: 'unknown', initial: '' },
  height: { themeKey: 'sizes', initial: '' },
  'hyphenate-character': { themeKey: 'unknown', initial: '' },
  'hyphenate-limit-chars': { themeKey: 'unknown', initial: '' },
  hyphens: { themeKey: 'unknown', initial: '' },
  'image-orientation': { themeKey: 'unknown', initial: '' },
  'image-rendering': { themeKey: 'unknown', initial: '' },
  'image-resolution': { themeKey: 'unknown', initial: '' },
  'initial-letter': { themeKey: 'unknown', initial: '' },
  'inline-size': { themeKey: 'sizes', initial: '' },
  'input-security': { themeKey: 'unknown', initial: '' },
  inset: { themeKey: 'grid', initial: '0' },
  'inset-block': { themeKey: 'grid', initial: '0' },
  'inset-block-end': { themeKey: 'grid', initial: '0' },
  'inset-block-start': { themeKey: 'grid', initial: '0' },
  'inset-inline': { themeKey: 'grid', initial: '0' },
  'inset-inline-end': { themeKey: 'grid', initial: '0' },
  'inset-inline-start': { themeKey: 'grid', initial: '0' },
  isolation: { themeKey: 'unknown', initial: '' },
  'justify-content': { themeKey: 'unknown', initial: '' },
  'justify-items': { themeKey: 'unknown', initial: '' },
  'justify-self': { themeKey: 'unknown', initial: '' },
  'justify-tracks': { themeKey: 'unknown', initial: '' },
  left: { themeKey: 'grid', initial: '0' },
  'letter-spacing': { themeKey: 'letterSpacings', initial: '' },
  'line-break': { themeKey: 'unknown', initial: '' },
  'line-clamp': { themeKey: 'unknown', initial: '' },
  'line-height': { themeKey: 'lineHeights', initial: '' },
  'line-height-step': { themeKey: 'unknown', initial: '' },
  'list-style': { themeKey: 'unknown', initial: '' },
  'list-style-image': { themeKey: 'unknown', initial: '' },
  'list-style-position': { themeKey: 'unknown', initial: '' },
  'list-style-type': { themeKey: 'unknown', initial: '' },
  margin: { themeKey: 'grid', initial: '0' },
  'margin-block': { themeKey: 'grid', initial: '0' },
  'margin-block-end': { themeKey: 'grid', initial: '0' },
  'margin-block-start': { themeKey: 'grid', initial: '0' },
  'margin-bottom': { themeKey: 'grid', initial: '0' },
  'margin-inline': { themeKey: 'grid', initial: '0' },
  'margin-inline-end': { themeKey: 'grid', initial: '0' },
  'margin-inline-start': { themeKey: 'grid', initial: '0' },
  'margin-left': { themeKey: 'grid', initial: '0' },
  'margin-right': { themeKey: 'grid', initial: '0' },
  'margin-top': { themeKey: 'grid', initial: '0' },
  'margin-trim': { themeKey: 'unknown', initial: '' },
  mask: { themeKey: 'unknown', initial: '' },
  'mask-border': { themeKey: 'unknown', initial: '' },
  'mask-border-mode': { themeKey: 'unknown', initial: '' },
  'mask-border-outset': { themeKey: 'unknown', initial: '' },
  'mask-border-repeat': { themeKey: 'unknown', initial: '' },
  'mask-border-slice': { themeKey: 'unknown', initial: '' },
  'mask-border-source': { themeKey: 'unknown', initial: '' },
  'mask-border-width': { themeKey: 'unknown', initial: '' },
  'mask-clip': { themeKey: 'unknown', initial: '' },
  'mask-composite': { themeKey: 'unknown', initial: '' },
  'mask-image': { themeKey: 'unknown', initial: '' },
  'mask-mode': { themeKey: 'unknown', initial: '' },
  'mask-origin': { themeKey: 'unknown', initial: '' },
  'mask-position': { themeKey: 'unknown', initial: '' },
  'mask-repeat': { themeKey: 'unknown', initial: '' },
  'mask-size': { themeKey: 'unknown', initial: '' },
  'mask-type': { themeKey: 'unknown', initial: '' },
  'math-depth': { themeKey: 'unknown', initial: '' },
  'math-shift': { themeKey: 'unknown', initial: '' },
  'math-style': { themeKey: 'unknown', initial: '' },
  'max-block-size': { themeKey: 'sizes', initial: '' },
  'max-height': { themeKey: 'sizes', initial: '' },
  'max-inline-size': { themeKey: 'sizes', initial: '' },
  'max-lines': { themeKey: 'unknown', initial: '' },
  'max-width': { themeKey: 'sizes', initial: '' },
  'min-block-size': { themeKey: 'sizes', initial: '' },
  'min-height': { themeKey: 'sizes', initial: '' },
  'min-inline-size': { themeKey: 'sizes', initial: '' },
  'min-width': { themeKey: 'sizes', initial: '' },
  'mix-blend-mode': { themeKey: 'unknown', initial: '' },
  'object-fit': { themeKey: 'unknown', initial: '' },
  'object-position': { themeKey: 'unknown', initial: '' },
  offset: { themeKey: 'unknown', initial: '' },
  'offset-anchor': { themeKey: 'unknown', initial: '' },
  'offset-distance': { themeKey: 'unknown', initial: '' },
  'offset-path': { themeKey: 'unknown', initial: '' },
  'offset-position': { themeKey: 'unknown', initial: '' },
  'offset-rotate': { themeKey: 'unknown', initial: '' },
  opacity: { themeKey: 'opacities', initial: '' },
  order: { themeKey: 'unknown', initial: '' },
  orphans: { themeKey: 'unknown', initial: '' },
  outline: { themeKey: 'unknown', initial: '' },
  'outline-color': { themeKey: 'colors', initial: '' },
  'outline-offset': { themeKey: 'unknown', initial: '' },
  'outline-style': { themeKey: 'unknown', initial: '' },
  'outline-width': { themeKey: 'unknown', initial: '' },
  overflow: { themeKey: 'unknown', initial: '' },
  'overflow-anchor': { themeKey: 'unknown', initial: '' },
  'overflow-block': { themeKey: 'unknown', initial: '' },
  'overflow-clip-margin': { themeKey: 'unknown', initial: '' },
  'overflow-inline': { themeKey: 'unknown', initial: '' },
  'overflow-wrap': { themeKey: 'unknown', initial: '' },
  'overflow-x': { themeKey: 'unknown', initial: '' },
  'overflow-y': { themeKey: 'unknown', initial: '' },
  'overscroll-behavior': { themeKey: 'unknown', initial: '' },
  'overscroll-behavior-block': { themeKey: 'unknown', initial: '' },
  'overscroll-behavior-inline': { themeKey: 'unknown', initial: '' },
  'overscroll-behavior-x': { themeKey: 'unknown', initial: '' },
  'overscroll-behavior-y': { themeKey: 'unknown', initial: '' },
  padding: { themeKey: 'grid', initial: '0' },
  'padding-block': { themeKey: 'grid', initial: '0' },
  'padding-block-end': { themeKey: 'grid', initial: '0' },
  'padding-block-start': { themeKey: 'grid', initial: '0' },
  'padding-bottom': { themeKey: 'grid', initial: '0' },
  'padding-inline': { themeKey: 'grid', initial: '0' },
  'padding-inline-end': { themeKey: 'grid', initial: '0' },
  'padding-inline-start': { themeKey: 'grid', initial: '0' },
  'padding-left': { themeKey: 'grid', initial: '0' },
  'padding-right': { themeKey: 'grid', initial: '0' },
  'padding-top': { themeKey: 'grid', initial: '0' },
  page: { themeKey: 'unknown', initial: '' },
  'page-break-after': { themeKey: 'unknown', initial: '' },
  'page-break-before': { themeKey: 'unknown', initial: '' },
  'page-break-inside': { themeKey: 'unknown', initial: '' },
  'paint-order': { themeKey: 'unknown', initial: '' },
  perspective: { themeKey: 'unknown', initial: '' },
  'perspective-origin': { themeKey: 'unknown', initial: '' },
  'place-content': { themeKey: 'unknown', initial: '' },
  'place-items': { themeKey: 'unknown', initial: '' },
  'place-self': { themeKey: 'unknown', initial: '' },
  'pointer-events': { themeKey: 'unknown', initial: '' },
  position: { themeKey: 'unknown', initial: '' },
  'print-color-adjust': { themeKey: 'unknown', initial: '' },
  quotes: { themeKey: 'unknown', initial: '' },
  resize: { themeKey: 'unknown', initial: '' },
  right: { themeKey: 'grid', initial: '0' },
  rotate: { themeKey: 'unknown', initial: '' },
  'row-gap': { themeKey: 'grid', initial: '0' },
  'ruby-align': { themeKey: 'unknown', initial: '' },
  'ruby-merge': { themeKey: 'unknown', initial: '' },
  'ruby-position': { themeKey: 'unknown', initial: '' },
  scale: { themeKey: 'unknown', initial: '' },
  'scroll-behavior': { themeKey: 'unknown', initial: '' },
  'scroll-margin': { themeKey: 'grid', initial: '0' },
  'scroll-margin-block': { themeKey: 'unknown', initial: '' },
  'scroll-margin-block-end': { themeKey: 'unknown', initial: '' },
  'scroll-margin-block-start': { themeKey: 'unknown', initial: '' },
  'scroll-margin-bottom': { themeKey: 'grid', initial: '0' },
  'scroll-margin-inline': { themeKey: 'unknown', initial: '' },
  'scroll-margin-inline-end': { themeKey: 'unknown', initial: '' },
  'scroll-margin-inline-start': { themeKey: 'unknown', initial: '' },
  'scroll-margin-left': { themeKey: 'grid', initial: '0' },
  'scroll-margin-right': { themeKey: 'grid', initial: '0' },
  'scroll-margin-top': { themeKey: 'grid', initial: '0' },
  'scroll-padding': { themeKey: 'grid', initial: '0' },
  'scroll-padding-block': { themeKey: 'unknown', initial: '' },
  'scroll-padding-block-end': { themeKey: 'unknown', initial: '' },
  'scroll-padding-block-start': { themeKey: 'unknown', initial: '' },
  'scroll-padding-bottom': { themeKey: 'grid', initial: '0' },
  'scroll-padding-inline': { themeKey: 'unknown', initial: '' },
  'scroll-padding-inline-end': { themeKey: 'unknown', initial: '' },
  'scroll-padding-inline-start': { themeKey: 'unknown', initial: '' },
  'scroll-padding-left': { themeKey: 'grid', initial: '0' },
  'scroll-padding-right': { themeKey: 'grid', initial: '0' },
  'scroll-padding-top': { themeKey: 'grid', initial: '0' },
  'scroll-snap-align': { themeKey: 'unknown', initial: '' },
  'scroll-snap-stop': { themeKey: 'unknown', initial: '' },
  'scroll-snap-type': { themeKey: 'unknown', initial: '' },
  'scroll-timeline': { themeKey: 'unknown', initial: '' },
  'scroll-timeline-axis': { themeKey: 'unknown', initial: '' },
  'scroll-timeline-name': { themeKey: 'unknown', initial: '' },
  'scrollbar-color': { themeKey: 'unknown', initial: '' },
  'scrollbar-gutter': { themeKey: 'unknown', initial: '' },
  'scrollbar-width': { themeKey: 'unknown', initial: '' },
  'shape-image-threshold': { themeKey: 'unknown', initial: '' },
  'shape-margin': { themeKey: 'unknown', initial: '' },
  'shape-outside': { themeKey: 'unknown', initial: '' },
  'tab-size': { themeKey: 'unknown', initial: '' },
  'table-layout': { themeKey: 'unknown', initial: '' },
  'text-align': { themeKey: 'unknown', initial: '' },
  'text-align-last': { themeKey: 'unknown', initial: '' },
  'text-combine-upright': { themeKey: 'unknown', initial: '' },
  'text-decoration': { themeKey: 'unknown', initial: '' },
  'text-decoration-color': { themeKey: 'colors', initial: '' },
  'text-decoration-line': { themeKey: 'unknown', initial: '' },
  'text-decoration-skip': { themeKey: 'unknown', initial: '' },
  'text-decoration-skip-ink': { themeKey: 'unknown', initial: '' },
  'text-decoration-style': { themeKey: 'unknown', initial: '' },
  'text-decoration-thickness': { themeKey: 'unknown', initial: '' },
  'text-emphasis': { themeKey: 'unknown', initial: '' },
  'text-emphasis-color': { themeKey: 'unknown', initial: '' },
  'text-emphasis-position': { themeKey: 'unknown', initial: '' },
  'text-emphasis-style': { themeKey: 'unknown', initial: '' },
  'text-indent': { themeKey: 'unknown', initial: '' },
  'text-justify': { themeKey: 'unknown', initial: '' },
  'text-orientation': { themeKey: 'unknown', initial: '' },
  'text-overflow': { themeKey: 'unknown', initial: '' },
  'text-rendering': { themeKey: 'unknown', initial: '' },
  'text-shadow': { themeKey: 'shadows', initial: '' },
  'text-size-adjust': { themeKey: 'unknown', initial: '' },
  'text-transform': { themeKey: 'unknown', initial: '' },
  'text-underline-offset': { themeKey: 'unknown', initial: '' },
  'text-underline-position': { themeKey: 'unknown', initial: '' },
  top: { themeKey: 'grid', initial: '0' },
  'touch-action': { themeKey: 'unknown', initial: '' },
  transform: { themeKey: 'unknown', initial: '' },
  'transform-box': { themeKey: 'unknown', initial: '' },
  'transform-origin': { themeKey: 'unknown', initial: '' },
  'transform-style': { themeKey: 'unknown', initial: '' },
  transition: { themeKey: 'transitions', initial: '' },
  'transition-delay': { themeKey: 'unknown', initial: '' },
  'transition-duration': { themeKey: 'unknown', initial: '' },
  'transition-property': { themeKey: 'unknown', initial: '' },
  'transition-timing-function': { themeKey: 'unknown', initial: '' },
  translate: { themeKey: 'unknown', initial: '' },
  'unicode-bidi': { themeKey: 'unknown', initial: '' },
  'user-select': { themeKey: 'unknown', initial: '' },
  'vertical-align': { themeKey: 'unknown', initial: '' },
  'view-transition-name': { themeKey: 'unknown', initial: '' },
  visibility: { themeKey: 'unknown', initial: '' },
  'white-space': { themeKey: 'unknown', initial: '' },
  widows: { themeKey: 'unknown', initial: '' },
  width: { themeKey: 'sizes', initial: '' },
  'will-change': { themeKey: 'unknown', initial: '' },
  'word-break': { themeKey: 'unknown', initial: '' },
  'word-spacing': { themeKey: 'unknown', initial: '' },
  'word-wrap': { themeKey: 'unknown', initial: '' },
  'writing-mode': { themeKey: 'unknown', initial: '' },
  'z-index': { themeKey: 'zIndices', initial: '' },
  zoom: { themeKey: 'unknown', initial: '' },
} satisfies Partial<Record<keyof CSS.PropertiesHyphen, PropertyConfig>>;

const pseudoClasses: CSS.SimplePseudos[] = [
  ':active',
  ':any-link',
  ':blank',
  ':checked',
  ':current',
  ':default',
  ':defined',
  ':disabled',
  ':empty',
  ':enabled',
  ':first',
  ':first-child',
  ':first-of-type',
  ':focus',
  ':focus-visible',
  ':focus-within',
  ':fullscreen',
  ':future',
  ':hover',
  ':in-range',
  ':indeterminate',
  ':invalid',
  ':last-child',
  ':last-of-type',
  ':left',
  ':link',
  ':local-link',
  ':nth-col',
  ':nth-last-col',
  ':only-child',
  ':only-of-type',
  ':optional',
  ':out-of-range',
  ':past',
  ':paused',
  ':picture-in-picture',
  ':placeholder-shown',
  ':playing',
  ':read-only',
  ':read-write',
  ':required',
  ':right',
  ':root',
  ':scope',
  ':target',
  ':target-within',
  ':user-invalid',
  ':user-valid',
  ':valid',
  ':visited',
];

const pseudoElements: CSS.SimplePseudos[] = [
  '::after',
  '::backdrop',
  '::before',
  '::cue',
  '::cue-region',
  '::first-letter',
  '::first-line',
  '::grammar-error',
  '::marker',
  '::placeholder',
  '::selection',
  '::spelling-error',
  '::target-text',
  '::view-transition',
];

type TokenamiProperty = keyof typeof themeConfig;
const properties = Object.keys(themeConfig) as TokenamiProperty[];
const SHEET_CONFIG = { themeConfig, properties, pseudoClasses, pseudoElements };

/* ---------------------------------------------------------------------------------------------- */

export type { TokenamiProperty, Theme };
export { SHEET_CONFIG };
