import type * as CSS from 'csstype';
import type * as Tokenami from '@tokenami/config';

// consumer will override this interface
interface TokenamiConfig {}

type Merge<A, B> = B extends never ? A : Omit<A, keyof B> & B;

type DefaultConfig = Tokenami.DefaultConfig & { CI: false };
interface TokenamiFinalConfig extends Merge<DefaultConfig, TokenamiConfig> {}

type ThemeConfig = TokenamiFinalConfig['theme'];
type AliasConfig = TokenamiFinalConfig['aliases'];
type PropertyConfig = TokenamiFinalConfig['properties'];

type Theme = ThemeConfig extends Tokenami.ThemeModes<infer T> ? T : ThemeConfig;
type SelectorKey = keyof TokenamiFinalConfig['selectors'];
type ResponsiveKey = keyof TokenamiFinalConfig['responsive'];
type ResponsiveSelectorKey = `${ResponsiveKey}_${SelectorKey}`;

type TokensByThemeKey = {
  [K in keyof Theme]: keyof Theme[K] extends `${infer Token}`
    ? Tokenami.TokenValue<K, Token>
    : never;
};

type GridOrThemeValue<ThemeKey> = ThemeKey extends 'grid'
  ? Tokenami.GridValue
  : ThemeKey extends keyof TokensByThemeKey
  ? TokensByThemeKey[ThemeKey]
  : never;

type PropertyThemeValue<ThemeKey> = ThemeKey extends 'grid' | keyof TokensByThemeKey
  ? Tokenami.ArbitraryValue | CSS.Globals | GridOrThemeValue<ThemeKey>
  : never;

type VariantProperty<P extends string> =
  | Tokenami.TokenProperty<P>
  | (TokenamiFinalConfig['CI'] extends true
      ? Tokenami.VariantProperty<P, ResponsiveKey | SelectorKey | ResponsiveSelectorKey>
      : Tokenami.VariantProperty<P, string>);

type AliasedProperty<P> = {
  [A in keyof AliasConfig]: P extends AliasConfig[A][number] ? VariantProperty<A> : never;
}[keyof AliasConfig];

type TokenProperty<P> = P extends string
  ? AliasedProperty<P> extends never
    ? VariantProperty<P>
    : AliasedProperty<P> | VariantProperty<P>
  : never;

type TokenValue<P> = P extends keyof PropertyConfig
  ? PropertyThemeValue<PropertyConfig[P][number]>
  : never;

type PropertyTokens<P> = {
  [K in TokenProperty<P>]?: TokenValue<P> extends never
    ? P extends keyof Tokenami.CSSProperties
      ? Tokenami.CSSProperties[P]
      : never
    : TokenValue<P>;
};

interface Property {
  all: PropertyTokens<'all'>;
  animation: PropertyTokens<'animation'>;
  'animation-range': PropertyTokens<'animation-range'>;
  background: PropertyTokens<'background'>;
  'background-position': PropertyTokens<'background-position'>;
  border: PropertyTokens<'border'>;
  'border-bottom': PropertyTokens<'border-bottom'>;
  'border-color': PropertyTokens<'border-color'>;
  'border-image': PropertyTokens<'border-image'>;
  'border-left': PropertyTokens<'border-left'>;
  'border-radius': PropertyTokens<'border-radius'>;
  'border-right': PropertyTokens<'border-right'>;
  'border-style': PropertyTokens<'border-style'>;
  'border-top': PropertyTokens<'border-top'>;
  'border-width': PropertyTokens<'border-width'>;
  caret: PropertyTokens<'caret'>;
  'column-rule': PropertyTokens<'column-rule'>;
  columns: PropertyTokens<'columns'>;
  'contain-intrinsic-size': PropertyTokens<'contain-intrinsic-size'>;
  container: PropertyTokens<'container'>;
  flex: PropertyTokens<'flex'>;
  'flex-flow': PropertyTokens<'flex-flow'>;
  font: PropertyTokens<'font'>;
  gap: PropertyTokens<'gap'>;
  grid: PropertyTokens<'grid'>;
  'grid-area': PropertyTokens<'grid-area'>;
  'grid-column': PropertyTokens<'grid-column'>;
  'grid-row': PropertyTokens<'grid-row'>;
  'grid-template': PropertyTokens<'grid-template'>;
  inset: PropertyTokens<'inset'>;
  'line-clamp': PropertyTokens<'line-clamp'>;
  'list-style': PropertyTokens<'list-style'>;
  margin: PropertyTokens<'margin'>;
  mask: PropertyTokens<'mask'>;
  'mask-border': PropertyTokens<'mask-border'>;
  motion: PropertyTokens<'motion'>;
  offset: PropertyTokens<'offset'>;
  outline: PropertyTokens<'outline'>;
  overflow: PropertyTokens<'overflow'>;
  'overscroll-behavior': PropertyTokens<'overscroll-behavior'>;
  padding: PropertyTokens<'padding'>;
  'place-content': PropertyTokens<'place-content'>;
  'place-items': PropertyTokens<'place-items'>;
  'place-self': PropertyTokens<'place-self'>;
  'scroll-margin': PropertyTokens<'scroll-margin'>;
  'scroll-padding': PropertyTokens<'scroll-padding'>;
  'scroll-snap-margin': PropertyTokens<'scroll-snap-margin'>;
  'scroll-timeline': PropertyTokens<'scroll-timeline'>;
  'text-decoration': PropertyTokens<'text-decoration'>;
  'text-emphasis': PropertyTokens<'text-emphasis'>;
  transition: PropertyTokens<'transition'>;
  'view-timeline': PropertyTokens<'view-timeline'>;
  'accent-color': PropertyTokens<'accent-color'>;
  'align-content': PropertyTokens<'align-content'>;
  'align-items': PropertyTokens<'align-items'>;
  'align-self': PropertyTokens<'align-self'>;
  'align-tracks': PropertyTokens<'align-tracks'>;
  'animation-composition': PropertyTokens<'animation-composition'>;
  'animation-delay': PropertyTokens<'animation-delay'>;
  'animation-direction': PropertyTokens<'animation-direction'>;
  'animation-duration': PropertyTokens<'animation-duration'>;
  'animation-fill-mode': PropertyTokens<'animation-fill-mode'>;
  'animation-iteration-count': PropertyTokens<'animation-iteration-count'>;
  'animation-name': PropertyTokens<'animation-name'>;
  'animation-play-state': PropertyTokens<'animation-play-state'>;
  'animation-range-end': PropertyTokens<'animation-range-end'>;
  'animation-range-start': PropertyTokens<'animation-range-start'>;
  'animation-timeline': PropertyTokens<'animation-timeline'>;
  'animation-timing-function': PropertyTokens<'animation-timing-function'>;
  appearance: PropertyTokens<'appearance'>;
  'aspect-ratio': PropertyTokens<'aspect-ratio'>;
  'backdrop-filter': PropertyTokens<'backdrop-filter'>;
  'backface-visibility': PropertyTokens<'backface-visibility'>;
  'background-attachment': PropertyTokens<'background-attachment'>;
  'background-blend-mode': PropertyTokens<'background-blend-mode'>;
  'background-clip': PropertyTokens<'background-clip'>;
  'background-color': PropertyTokens<'background-color'>;
  'background-image': PropertyTokens<'background-image'>;
  'background-origin': PropertyTokens<'background-origin'>;
  'background-position-x': PropertyTokens<'background-position-x'>;
  'background-position-y': PropertyTokens<'background-position-y'>;
  'background-repeat': PropertyTokens<'background-repeat'>;
  'background-size': PropertyTokens<'background-size'>;
  'border-bottom-color': PropertyTokens<'border-bottom-color'>;
  'border-bottom-left-radius': PropertyTokens<'border-bottom-left-radius'>;
  'border-bottom-right-radius': PropertyTokens<'border-bottom-right-radius'>;
  'border-bottom-style': PropertyTokens<'border-bottom-style'>;
  'border-bottom-width': PropertyTokens<'border-bottom-width'>;
  'border-collapse': PropertyTokens<'border-collapse'>;
  'border-end-end-radius': PropertyTokens<'border-end-end-radius'>;
  'border-end-start-radius': PropertyTokens<'border-end-start-radius'>;
  'border-image-outset': PropertyTokens<'border-image-outset'>;
  'border-image-repeat': PropertyTokens<'border-image-repeat'>;
  'border-image-slice': PropertyTokens<'border-image-slice'>;
  'border-image-source': PropertyTokens<'border-image-source'>;
  'border-image-width': PropertyTokens<'border-image-width'>;
  'border-left-color': PropertyTokens<'border-left-color'>;
  'border-left-style': PropertyTokens<'border-left-style'>;
  'border-left-width': PropertyTokens<'border-left-width'>;
  'border-right-color': PropertyTokens<'border-right-color'>;
  'border-right-style': PropertyTokens<'border-right-style'>;
  'border-right-width': PropertyTokens<'border-right-width'>;
  'border-spacing': PropertyTokens<'border-spacing'>;
  'border-start-end-radius': PropertyTokens<'border-start-end-radius'>;
  'border-start-start-radius': PropertyTokens<'border-start-start-radius'>;
  'border-top-color': PropertyTokens<'border-top-color'>;
  'border-top-left-radius': PropertyTokens<'border-top-left-radius'>;
  'border-top-right-radius': PropertyTokens<'border-top-right-radius'>;
  'border-top-style': PropertyTokens<'border-top-style'>;
  'border-top-width': PropertyTokens<'border-top-width'>;
  bottom: PropertyTokens<'bottom'>;
  'box-decoration-break': PropertyTokens<'box-decoration-break'>;
  'box-shadow': PropertyTokens<'box-shadow'>;
  'box-sizing': PropertyTokens<'box-sizing'>;
  'break-after': PropertyTokens<'break-after'>;
  'break-before': PropertyTokens<'break-before'>;
  'break-inside': PropertyTokens<'break-inside'>;
  'caption-side': PropertyTokens<'caption-side'>;
  'caret-color': PropertyTokens<'caret-color'>;
  'caret-shape': PropertyTokens<'caret-shape'>;
  clear: PropertyTokens<'clear'>;
  'clip-path': PropertyTokens<'clip-path'>;
  color: PropertyTokens<'color'>;
  'color-adjust': PropertyTokens<'color-adjust'>;
  'color-scheme': PropertyTokens<'color-scheme'>;
  'column-count': PropertyTokens<'column-count'>;
  'column-fill': PropertyTokens<'column-fill'>;
  'column-gap': PropertyTokens<'column-gap'>;
  'column-rule-color': PropertyTokens<'column-rule-color'>;
  'column-rule-style': PropertyTokens<'column-rule-style'>;
  'column-rule-width': PropertyTokens<'column-rule-width'>;
  'column-span': PropertyTokens<'column-span'>;
  'column-width': PropertyTokens<'column-width'>;
  contain: PropertyTokens<'contain'>;
  'contain-intrinsic-height': PropertyTokens<'contain-intrinsic-height'>;
  'contain-intrinsic-width': PropertyTokens<'contain-intrinsic-width'>;
  'container-name': PropertyTokens<'container-name'>;
  'container-type': PropertyTokens<'container-type'>;
  content: PropertyTokens<'content'>;
  'content-visibility': PropertyTokens<'content-visibility'>;
  'counter-increment': PropertyTokens<'counter-increment'>;
  'counter-reset': PropertyTokens<'counter-reset'>;
  'counter-set': PropertyTokens<'counter-set'>;
  cursor: PropertyTokens<'cursor'>;
  direction: PropertyTokens<'direction'>;
  display: PropertyTokens<'display'>;
  'empty-cells': PropertyTokens<'empty-cells'>;
  filter: PropertyTokens<'filter'>;
  'flex-basis': PropertyTokens<'flex-basis'>;
  'flex-direction': PropertyTokens<'flex-direction'>;
  'flex-grow': PropertyTokens<'flex-grow'>;
  'flex-shrink': PropertyTokens<'flex-shrink'>;
  'flex-wrap': PropertyTokens<'flex-wrap'>;
  float: PropertyTokens<'float'>;
  'font-family': PropertyTokens<'font-family'>;
  'font-feature-settings': PropertyTokens<'font-feature-settings'>;
  'font-kerning': PropertyTokens<'font-kerning'>;
  'font-language-override': PropertyTokens<'font-language-override'>;
  'font-optical-sizing': PropertyTokens<'font-optical-sizing'>;
  'font-palette': PropertyTokens<'font-palette'>;
  'font-size': PropertyTokens<'font-size'>;
  'font-size-adjust': PropertyTokens<'font-size-adjust'>;
  'font-smooth': PropertyTokens<'font-smooth'>;
  'font-stretch': PropertyTokens<'font-stretch'>;
  'font-style': PropertyTokens<'font-style'>;
  'font-synthesis': PropertyTokens<'font-synthesis'>;
  'font-synthesis-position': PropertyTokens<'font-synthesis-position'>;
  'font-synthesis-small-caps': PropertyTokens<'font-synthesis-small-caps'>;
  'font-synthesis-style': PropertyTokens<'font-synthesis-style'>;
  'font-synthesis-weight': PropertyTokens<'font-synthesis-weight'>;
  'font-variant': PropertyTokens<'font-variant'>;
  'font-variant-alternates': PropertyTokens<'font-variant-alternates'>;
  'font-variant-caps': PropertyTokens<'font-variant-caps'>;
  'font-variant-east-asian': PropertyTokens<'font-variant-east-asian'>;
  'font-variant-emoji': PropertyTokens<'font-variant-emoji'>;
  'font-variant-ligatures': PropertyTokens<'font-variant-ligatures'>;
  'font-variant-numeric': PropertyTokens<'font-variant-numeric'>;
  'font-variant-position': PropertyTokens<'font-variant-position'>;
  'font-variation-settings': PropertyTokens<'font-variation-settings'>;
  'font-weight': PropertyTokens<'font-weight'>;
  'forced-color-adjust': PropertyTokens<'forced-color-adjust'>;
  'grid-auto-columns': PropertyTokens<'grid-auto-columns'>;
  'grid-auto-flow': PropertyTokens<'grid-auto-flow'>;
  'grid-auto-rows': PropertyTokens<'grid-auto-rows'>;
  'grid-column-end': PropertyTokens<'grid-column-end'>;
  'grid-column-start': PropertyTokens<'grid-column-start'>;
  'grid-row-end': PropertyTokens<'grid-row-end'>;
  'grid-row-start': PropertyTokens<'grid-row-start'>;
  'grid-template-areas': PropertyTokens<'grid-template-areas'>;
  'grid-template-columns': PropertyTokens<'grid-template-columns'>;
  'grid-template-rows': PropertyTokens<'grid-template-rows'>;
  'hanging-punctuation': PropertyTokens<'hanging-punctuation'>;
  height: PropertyTokens<'height'>;
  'hyphenate-character': PropertyTokens<'hyphenate-character'>;
  'hyphenate-limit-chars': PropertyTokens<'hyphenate-limit-chars'>;
  hyphens: PropertyTokens<'hyphens'>;
  'image-orientation': PropertyTokens<'image-orientation'>;
  'image-rendering': PropertyTokens<'image-rendering'>;
  'image-resolution': PropertyTokens<'image-resolution'>;
  'initial-letter': PropertyTokens<'initial-letter'>;
  'input-security': PropertyTokens<'input-security'>;
  isolation: PropertyTokens<'isolation'>;
  'justify-content': PropertyTokens<'justify-content'>;
  'justify-items': PropertyTokens<'justify-items'>;
  'justify-self': PropertyTokens<'justify-self'>;
  'justify-tracks': PropertyTokens<'justify-tracks'>;
  left: PropertyTokens<'left'>;
  'letter-spacing': PropertyTokens<'letter-spacing'>;
  'line-break': PropertyTokens<'line-break'>;
  'line-height': PropertyTokens<'line-height'>;
  'line-height-step': PropertyTokens<'line-height-step'>;
  'list-style-image': PropertyTokens<'list-style-image'>;
  'list-style-position': PropertyTokens<'list-style-position'>;
  'list-style-type': PropertyTokens<'list-style-type'>;
  'margin-bottom': PropertyTokens<'margin-bottom'>;
  'margin-left': PropertyTokens<'margin-left'>;
  'margin-right': PropertyTokens<'margin-right'>;
  'margin-top': PropertyTokens<'margin-top'>;
  'margin-trim': PropertyTokens<'margin-trim'>;
  'mask-border-mode': PropertyTokens<'mask-border-mode'>;
  'mask-border-outset': PropertyTokens<'mask-border-outset'>;
  'mask-border-repeat': PropertyTokens<'mask-border-repeat'>;
  'mask-border-slice': PropertyTokens<'mask-border-slice'>;
  'mask-border-source': PropertyTokens<'mask-border-source'>;
  'mask-border-width': PropertyTokens<'mask-border-width'>;
  'mask-clip': PropertyTokens<'mask-clip'>;
  'mask-composite': PropertyTokens<'mask-composite'>;
  'mask-image': PropertyTokens<'mask-image'>;
  'mask-mode': PropertyTokens<'mask-mode'>;
  'mask-origin': PropertyTokens<'mask-origin'>;
  'mask-position': PropertyTokens<'mask-position'>;
  'mask-repeat': PropertyTokens<'mask-repeat'>;
  'mask-size': PropertyTokens<'mask-size'>;
  'mask-type': PropertyTokens<'mask-type'>;
  'masonry-auto-flow': PropertyTokens<'masonry-auto-flow'>;
  'math-depth': PropertyTokens<'math-depth'>;
  'math-shift': PropertyTokens<'math-shift'>;
  'math-style': PropertyTokens<'math-style'>;
  'max-height': PropertyTokens<'max-height'>;
  'max-lines': PropertyTokens<'max-lines'>;
  'max-width': PropertyTokens<'max-width'>;
  'min-height': PropertyTokens<'min-height'>;
  'min-width': PropertyTokens<'min-width'>;
  'mix-blend-mode': PropertyTokens<'mix-blend-mode'>;
  'motion-distance': PropertyTokens<'motion-distance'>;
  'motion-path': PropertyTokens<'motion-path'>;
  'motion-rotation': PropertyTokens<'motion-rotation'>;
  'object-fit': PropertyTokens<'object-fit'>;
  'object-position': PropertyTokens<'object-position'>;
  'offset-anchor': PropertyTokens<'offset-anchor'>;
  'offset-distance': PropertyTokens<'offset-distance'>;
  'offset-path': PropertyTokens<'offset-path'>;
  'offset-position': PropertyTokens<'offset-position'>;
  'offset-rotate': PropertyTokens<'offset-rotate'>;
  'offset-rotation': PropertyTokens<'offset-rotation'>;
  opacity: PropertyTokens<'opacity'>;
  order: PropertyTokens<'order'>;
  orphans: PropertyTokens<'orphans'>;
  'outline-color': PropertyTokens<'outline-color'>;
  'outline-offset': PropertyTokens<'outline-offset'>;
  'outline-style': PropertyTokens<'outline-style'>;
  'outline-width': PropertyTokens<'outline-width'>;
  'overflow-anchor': PropertyTokens<'overflow-anchor'>;
  'overflow-clip-box': PropertyTokens<'overflow-clip-box'>;
  'overflow-clip-margin': PropertyTokens<'overflow-clip-margin'>;
  'overflow-wrap': PropertyTokens<'overflow-wrap'>;
  'overflow-x': PropertyTokens<'overflow-x'>;
  'overflow-y': PropertyTokens<'overflow-y'>;
  overlay: PropertyTokens<'overlay'>;
  'overscroll-behavior-x': PropertyTokens<'overscroll-behavior-x'>;
  'overscroll-behavior-y': PropertyTokens<'overscroll-behavior-y'>;
  'padding-bottom': PropertyTokens<'padding-bottom'>;
  'padding-left': PropertyTokens<'padding-left'>;
  'padding-right': PropertyTokens<'padding-right'>;
  'padding-top': PropertyTokens<'padding-top'>;
  page: PropertyTokens<'page'>;
  'page-break-after': PropertyTokens<'page-break-after'>;
  'page-break-before': PropertyTokens<'page-break-before'>;
  'page-break-inside': PropertyTokens<'page-break-inside'>;
  'paint-order': PropertyTokens<'paint-order'>;
  perspective: PropertyTokens<'perspective'>;
  'perspective-origin': PropertyTokens<'perspective-origin'>;
  'pointer-events': PropertyTokens<'pointer-events'>;
  position: PropertyTokens<'position'>;
  'print-color-adjust': PropertyTokens<'print-color-adjust'>;
  quotes: PropertyTokens<'quotes'>;
  resize: PropertyTokens<'resize'>;
  right: PropertyTokens<'right'>;
  rotate: PropertyTokens<'rotate'>;
  'row-gap': PropertyTokens<'row-gap'>;
  'ruby-align': PropertyTokens<'ruby-align'>;
  'ruby-merge': PropertyTokens<'ruby-merge'>;
  'ruby-position': PropertyTokens<'ruby-position'>;
  scale: PropertyTokens<'scale'>;
  'scroll-behavior': PropertyTokens<'scroll-behavior'>;
  'scroll-margin-bottom': PropertyTokens<'scroll-margin-bottom'>;
  'scroll-margin-left': PropertyTokens<'scroll-margin-left'>;
  'scroll-margin-right': PropertyTokens<'scroll-margin-right'>;
  'scroll-margin-top': PropertyTokens<'scroll-margin-top'>;
  'scroll-padding-bottom': PropertyTokens<'scroll-padding-bottom'>;
  'scroll-padding-left': PropertyTokens<'scroll-padding-left'>;
  'scroll-padding-right': PropertyTokens<'scroll-padding-right'>;
  'scroll-padding-top': PropertyTokens<'scroll-padding-top'>;
  'scroll-snap-align': PropertyTokens<'scroll-snap-align'>;
  'scroll-snap-margin-bottom': PropertyTokens<'scroll-snap-margin-bottom'>;
  'scroll-snap-margin-left': PropertyTokens<'scroll-snap-margin-left'>;
  'scroll-snap-margin-right': PropertyTokens<'scroll-snap-margin-right'>;
  'scroll-snap-margin-top': PropertyTokens<'scroll-snap-margin-top'>;
  'scroll-snap-stop': PropertyTokens<'scroll-snap-stop'>;
  'scroll-snap-type': PropertyTokens<'scroll-snap-type'>;
  'scroll-timeline-axis': PropertyTokens<'scroll-timeline-axis'>;
  'scroll-timeline-name': PropertyTokens<'scroll-timeline-name'>;
  'scrollbar-color': PropertyTokens<'scrollbar-color'>;
  'scrollbar-gutter': PropertyTokens<'scrollbar-gutter'>;
  'scrollbar-width': PropertyTokens<'scrollbar-width'>;
  'shape-image-threshold': PropertyTokens<'shape-image-threshold'>;
  'shape-margin': PropertyTokens<'shape-margin'>;
  'shape-outside': PropertyTokens<'shape-outside'>;
  'tab-size': PropertyTokens<'tab-size'>;
  'table-layout': PropertyTokens<'table-layout'>;
  'text-align': PropertyTokens<'text-align'>;
  'text-align-last': PropertyTokens<'text-align-last'>;
  'text-combine-upright': PropertyTokens<'text-combine-upright'>;
  'text-decoration-color': PropertyTokens<'text-decoration-color'>;
  'text-decoration-line': PropertyTokens<'text-decoration-line'>;
  'text-decoration-skip': PropertyTokens<'text-decoration-skip'>;
  'text-decoration-skip-ink': PropertyTokens<'text-decoration-skip-ink'>;
  'text-decoration-style': PropertyTokens<'text-decoration-style'>;
  'text-decoration-thickness': PropertyTokens<'text-decoration-thickness'>;
  'text-emphasis-color': PropertyTokens<'text-emphasis-color'>;
  'text-emphasis-position': PropertyTokens<'text-emphasis-position'>;
  'text-emphasis-style': PropertyTokens<'text-emphasis-style'>;
  'text-indent': PropertyTokens<'text-indent'>;
  'text-justify': PropertyTokens<'text-justify'>;
  'text-orientation': PropertyTokens<'text-orientation'>;
  'text-overflow': PropertyTokens<'text-overflow'>;
  'text-rendering': PropertyTokens<'text-rendering'>;
  'text-shadow': PropertyTokens<'text-shadow'>;
  'text-size-adjust': PropertyTokens<'text-size-adjust'>;
  'text-transform': PropertyTokens<'text-transform'>;
  'text-underline-offset': PropertyTokens<'text-underline-offset'>;
  'text-underline-position': PropertyTokens<'text-underline-position'>;
  'text-wrap': PropertyTokens<'text-wrap'>;
  'timeline-scope': PropertyTokens<'timeline-scope'>;
  top: PropertyTokens<'top'>;
  'touch-action': PropertyTokens<'touch-action'>;
  transform: PropertyTokens<'transform'>;
  'transform-box': PropertyTokens<'transform-box'>;
  'transform-origin': PropertyTokens<'transform-origin'>;
  'transform-style': PropertyTokens<'transform-style'>;
  'transition-behavior': PropertyTokens<'transition-behavior'>;
  'transition-delay': PropertyTokens<'transition-delay'>;
  'transition-duration': PropertyTokens<'transition-duration'>;
  'transition-property': PropertyTokens<'transition-property'>;
  'transition-timing-function': PropertyTokens<'transition-timing-function'>;
  translate: PropertyTokens<'translate'>;
  'unicode-bidi': PropertyTokens<'unicode-bidi'>;
  'user-select': PropertyTokens<'user-select'>;
  'vertical-align': PropertyTokens<'vertical-align'>;
  'view-timeline-axis': PropertyTokens<'view-timeline-axis'>;
  'view-timeline-inset': PropertyTokens<'view-timeline-inset'>;
  'view-timeline-name': PropertyTokens<'view-timeline-name'>;
  'view-transition-name': PropertyTokens<'view-transition-name'>;
  visibility: PropertyTokens<'visibility'>;
  'white-space': PropertyTokens<'white-space'>;
  'white-space-collapse': PropertyTokens<'white-space-collapse'>;
  'white-space-trim': PropertyTokens<'white-space-trim'>;
  widows: PropertyTokens<'widows'>;
  width: PropertyTokens<'width'>;
  'will-change': PropertyTokens<'will-change'>;
  'word-break': PropertyTokens<'word-break'>;
  'word-spacing': PropertyTokens<'word-spacing'>;
  'word-wrap': PropertyTokens<'word-wrap'>;
  'writing-mode': PropertyTokens<'writing-mode'>;
  'z-index': PropertyTokens<'z-index'>;
  zoom: PropertyTokens<'zoom'>;
  'alignment-baseline': PropertyTokens<'alignment-baseline'>;
  'baseline-shift': PropertyTokens<'baseline-shift'>;
  clip: PropertyTokens<'clip'>;
  'clip-rule': PropertyTokens<'clip-rule'>;
  'color-interpolation': PropertyTokens<'color-interpolation'>;
  'color-rendering': PropertyTokens<'color-rendering'>;
  'dominant-baseline': PropertyTokens<'dominant-baseline'>;
  fill: PropertyTokens<'fill'>;
  'fill-opacity': PropertyTokens<'fill-opacity'>;
  'fill-rule': PropertyTokens<'fill-rule'>;
  'flood-color': PropertyTokens<'flood-color'>;
  'flood-opacity': PropertyTokens<'flood-opacity'>;
  'glyph-orientation-vertical': PropertyTokens<'glyph-orientation-vertical'>;
  'lighting-color': PropertyTokens<'lighting-color'>;
  marker: PropertyTokens<'marker'>;
  'marker-end': PropertyTokens<'marker-end'>;
  'marker-mid': PropertyTokens<'marker-mid'>;
  'marker-start': PropertyTokens<'marker-start'>;
  'shape-rendering': PropertyTokens<'shape-rendering'>;
  'stop-color': PropertyTokens<'stop-color'>;
  'stop-opacity': PropertyTokens<'stop-opacity'>;
  stroke: PropertyTokens<'stroke'>;
  'stroke-dasharray': PropertyTokens<'stroke-dasharray'>;
  'stroke-dashoffset': PropertyTokens<'stroke-dashoffset'>;
  'stroke-linecap': PropertyTokens<'stroke-linecap'>;
  'stroke-linejoin': PropertyTokens<'stroke-linejoin'>;
  'stroke-miterlimit': PropertyTokens<'stroke-miterlimit'>;
  'stroke-opacity': PropertyTokens<'stroke-opacity'>;
  'stroke-width': PropertyTokens<'stroke-width'>;
  'text-anchor': PropertyTokens<'text-anchor'>;
  'vector-effect': PropertyTokens<'vector-effect'>;
  'block-overflow': PropertyTokens<'block-overflow'>;
  'block-size': PropertyTokens<'block-size'>;
  'border-block': PropertyTokens<'border-block'>;
  'border-block-end': PropertyTokens<'border-block-end'>;
  'border-block-start': PropertyTokens<'border-block-start'>;
  'border-block-color': PropertyTokens<'border-block-color'>;
  'border-block-end-color': PropertyTokens<'border-block-end-color'>;
  'border-block-end-style': PropertyTokens<'border-block-end-style'>;
  'border-block-end-width': PropertyTokens<'border-block-end-width'>;
  'border-block-start-color': PropertyTokens<'border-block-start-color'>;
  'border-block-start-style': PropertyTokens<'border-block-start-style'>;
  'border-block-start-width': PropertyTokens<'border-block-start-width'>;
  'border-block-style': PropertyTokens<'border-block-style'>;
  'border-block-width': PropertyTokens<'border-block-width'>;
  'border-inline': PropertyTokens<'border-inline'>;
  'border-inline-end': PropertyTokens<'border-inline-end'>;
  'border-inline-start': PropertyTokens<'border-inline-start'>;
  'border-inline-color': PropertyTokens<'border-inline-color'>;
  'border-inline-end-color': PropertyTokens<'border-inline-end-color'>;
  'border-inline-end-style': PropertyTokens<'border-inline-end-style'>;
  'border-inline-end-width': PropertyTokens<'border-inline-end-width'>;
  'border-inline-start-color': PropertyTokens<'border-inline-start-color'>;
  'border-inline-start-style': PropertyTokens<'border-inline-start-style'>;
  'border-inline-start-width': PropertyTokens<'border-inline-start-width'>;
  'border-inline-style': PropertyTokens<'border-inline-style'>;
  'border-inline-width': PropertyTokens<'border-inline-width'>;
  'contain-intrinsic-block-size': PropertyTokens<'contain-intrinsic-block-size'>;
  'contain-intrinsic-inline-size': PropertyTokens<'contain-intrinsic-inline-size'>;
  'inline-size': PropertyTokens<'inline-size'>;
  'inset-block': PropertyTokens<'inset-block'>;
  'inset-block-end': PropertyTokens<'inset-block-end'>;
  'inset-block-start': PropertyTokens<'inset-block-start'>;
  'inset-inline': PropertyTokens<'inset-inline'>;
  'inset-inline-end': PropertyTokens<'inset-inline-end'>;
  'inset-inline-start': PropertyTokens<'inset-inline-start'>;
  'margin-block': PropertyTokens<'margin-block'>;
  'margin-block-end': PropertyTokens<'margin-block-end'>;
  'margin-block-start': PropertyTokens<'margin-block-start'>;
  'margin-inline': PropertyTokens<'margin-inline'>;
  'margin-inline-end': PropertyTokens<'margin-inline-end'>;
  'margin-inline-start': PropertyTokens<'margin-inline-start'>;
  'max-block-size': PropertyTokens<'max-block-size'>;
  'max-inline-size': PropertyTokens<'max-inline-size'>;
  'min-block-size': PropertyTokens<'min-block-size'>;
  'min-inline-size': PropertyTokens<'min-inline-size'>;
  'overflow-block': PropertyTokens<'overflow-block'>;
  'overflow-inline': PropertyTokens<'overflow-inline'>;
  'overscroll-behavior-block': PropertyTokens<'overscroll-behavior-block'>;
  'overscroll-behavior-inline': PropertyTokens<'overscroll-behavior-inline'>;
  'padding-block': PropertyTokens<'padding-block'>;
  'padding-block-end': PropertyTokens<'padding-block-end'>;
  'padding-block-start': PropertyTokens<'padding-block-start'>;
  'padding-inline': PropertyTokens<'padding-inline'>;
  'padding-inline-end': PropertyTokens<'padding-inline-end'>;
  'padding-inline-start': PropertyTokens<'padding-inline-start'>;
  'scroll-margin-block': PropertyTokens<'scroll-margin-block'>;
  'scroll-margin-block-end': PropertyTokens<'scroll-margin-block-end'>;
  'scroll-margin-block-start': PropertyTokens<'scroll-margin-block-start'>;
  'scroll-margin-inline': PropertyTokens<'scroll-margin-inline'>;
  'scroll-margin-inline-end': PropertyTokens<'scroll-margin-inline-end'>;
  'scroll-margin-inline-start': PropertyTokens<'scroll-margin-inline-start'>;
  'scroll-padding-block': PropertyTokens<'scroll-padding-block'>;
  'scroll-padding-block-end': PropertyTokens<'scroll-padding-block-end'>;
  'scroll-padding-block-start': PropertyTokens<'scroll-padding-block-start'>;
  'scroll-padding-inline': PropertyTokens<'scroll-padding-inline'>;
  'scroll-padding-inline-end': PropertyTokens<'scroll-padding-inline-end'>;
  'scroll-padding-inline-start': PropertyTokens<'scroll-padding-inline-start'>;
}

type Properties = PropertyTokens<'all'> &
  PropertyTokens<'animation'> &
  PropertyTokens<'animation-range'> &
  PropertyTokens<'background'> &
  PropertyTokens<'background-position'> &
  PropertyTokens<'border'> &
  PropertyTokens<'border-bottom'> &
  PropertyTokens<'border-color'> &
  PropertyTokens<'border-image'> &
  PropertyTokens<'border-left'> &
  PropertyTokens<'border-radius'> &
  PropertyTokens<'border-right'> &
  PropertyTokens<'border-style'> &
  PropertyTokens<'border-top'> &
  PropertyTokens<'border-width'> &
  PropertyTokens<'caret'> &
  PropertyTokens<'column-rule'> &
  PropertyTokens<'columns'> &
  PropertyTokens<'contain-intrinsic-size'> &
  PropertyTokens<'container'> &
  PropertyTokens<'flex'> &
  PropertyTokens<'flex-flow'> &
  PropertyTokens<'font'> &
  PropertyTokens<'gap'> &
  PropertyTokens<'grid'> &
  PropertyTokens<'grid-area'> &
  PropertyTokens<'grid-column'> &
  PropertyTokens<'grid-row'> &
  PropertyTokens<'grid-template'> &
  PropertyTokens<'inset'> &
  PropertyTokens<'line-clamp'> &
  PropertyTokens<'list-style'> &
  PropertyTokens<'margin'> &
  PropertyTokens<'mask'> &
  PropertyTokens<'mask-border'> &
  PropertyTokens<'motion'> &
  PropertyTokens<'offset'> &
  PropertyTokens<'outline'> &
  PropertyTokens<'overflow'> &
  PropertyTokens<'overscroll-behavior'> &
  PropertyTokens<'padding'> &
  PropertyTokens<'place-content'> &
  PropertyTokens<'place-items'> &
  PropertyTokens<'place-self'> &
  PropertyTokens<'scroll-margin'> &
  PropertyTokens<'scroll-padding'> &
  PropertyTokens<'scroll-snap-margin'> &
  PropertyTokens<'scroll-timeline'> &
  PropertyTokens<'text-decoration'> &
  PropertyTokens<'text-emphasis'> &
  PropertyTokens<'transition'> &
  PropertyTokens<'view-timeline'> &
  PropertyTokens<'accent-color'> &
  PropertyTokens<'align-content'> &
  PropertyTokens<'align-items'> &
  PropertyTokens<'align-self'> &
  PropertyTokens<'align-tracks'> &
  PropertyTokens<'animation-composition'> &
  PropertyTokens<'animation-delay'> &
  PropertyTokens<'animation-direction'> &
  PropertyTokens<'animation-duration'> &
  PropertyTokens<'animation-fill-mode'> &
  PropertyTokens<'animation-iteration-count'> &
  PropertyTokens<'animation-name'> &
  PropertyTokens<'animation-play-state'> &
  PropertyTokens<'animation-range-end'> &
  PropertyTokens<'animation-range-start'> &
  PropertyTokens<'animation-timeline'> &
  PropertyTokens<'animation-timing-function'> &
  PropertyTokens<'appearance'> &
  PropertyTokens<'aspect-ratio'> &
  PropertyTokens<'backdrop-filter'> &
  PropertyTokens<'backface-visibility'> &
  PropertyTokens<'background-attachment'> &
  PropertyTokens<'background-blend-mode'> &
  PropertyTokens<'background-clip'> &
  PropertyTokens<'background-color'> &
  PropertyTokens<'background-image'> &
  PropertyTokens<'background-origin'> &
  PropertyTokens<'background-position-x'> &
  PropertyTokens<'background-position-y'> &
  PropertyTokens<'background-repeat'> &
  PropertyTokens<'background-size'> &
  PropertyTokens<'border-bottom-color'> &
  PropertyTokens<'border-bottom-left-radius'> &
  PropertyTokens<'border-bottom-right-radius'> &
  PropertyTokens<'border-bottom-style'> &
  PropertyTokens<'border-bottom-width'> &
  PropertyTokens<'border-collapse'> &
  PropertyTokens<'border-end-end-radius'> &
  PropertyTokens<'border-end-start-radius'> &
  PropertyTokens<'border-image-outset'> &
  PropertyTokens<'border-image-repeat'> &
  PropertyTokens<'border-image-slice'> &
  PropertyTokens<'border-image-source'> &
  PropertyTokens<'border-image-width'> &
  PropertyTokens<'border-left-color'> &
  PropertyTokens<'border-left-style'> &
  PropertyTokens<'border-left-width'> &
  PropertyTokens<'border-right-color'> &
  PropertyTokens<'border-right-style'> &
  PropertyTokens<'border-right-width'> &
  PropertyTokens<'border-spacing'> &
  PropertyTokens<'border-start-end-radius'> &
  PropertyTokens<'border-start-start-radius'> &
  PropertyTokens<'border-top-color'> &
  PropertyTokens<'border-top-left-radius'> &
  PropertyTokens<'border-top-right-radius'> &
  PropertyTokens<'border-top-style'> &
  PropertyTokens<'border-top-width'> &
  PropertyTokens<'bottom'> &
  PropertyTokens<'box-decoration-break'> &
  PropertyTokens<'box-shadow'> &
  PropertyTokens<'box-sizing'> &
  PropertyTokens<'break-after'> &
  PropertyTokens<'break-before'> &
  PropertyTokens<'break-inside'> &
  PropertyTokens<'caption-side'> &
  PropertyTokens<'caret-color'> &
  PropertyTokens<'caret-shape'> &
  PropertyTokens<'clear'> &
  PropertyTokens<'clip-path'> &
  PropertyTokens<'color'> &
  PropertyTokens<'color-adjust'> &
  PropertyTokens<'color-scheme'> &
  PropertyTokens<'column-count'> &
  PropertyTokens<'column-fill'> &
  PropertyTokens<'column-gap'> &
  PropertyTokens<'column-rule-color'> &
  PropertyTokens<'column-rule-style'> &
  PropertyTokens<'column-rule-width'> &
  PropertyTokens<'column-span'> &
  PropertyTokens<'column-width'> &
  PropertyTokens<'contain'> &
  PropertyTokens<'contain-intrinsic-height'> &
  PropertyTokens<'contain-intrinsic-width'> &
  PropertyTokens<'container-name'> &
  PropertyTokens<'container-type'> &
  PropertyTokens<'content'> &
  PropertyTokens<'content-visibility'> &
  PropertyTokens<'counter-increment'> &
  PropertyTokens<'counter-reset'> &
  PropertyTokens<'counter-set'> &
  PropertyTokens<'cursor'> &
  PropertyTokens<'direction'> &
  PropertyTokens<'display'> &
  PropertyTokens<'empty-cells'> &
  PropertyTokens<'filter'> &
  PropertyTokens<'flex-basis'> &
  PropertyTokens<'flex-direction'> &
  PropertyTokens<'flex-grow'> &
  PropertyTokens<'flex-shrink'> &
  PropertyTokens<'flex-wrap'> &
  PropertyTokens<'float'> &
  PropertyTokens<'font-family'> &
  PropertyTokens<'font-feature-settings'> &
  PropertyTokens<'font-kerning'> &
  PropertyTokens<'font-language-override'> &
  PropertyTokens<'font-optical-sizing'> &
  PropertyTokens<'font-palette'> &
  PropertyTokens<'font-size'> &
  PropertyTokens<'font-size-adjust'> &
  PropertyTokens<'font-smooth'> &
  PropertyTokens<'font-stretch'> &
  PropertyTokens<'font-style'> &
  PropertyTokens<'font-synthesis'> &
  PropertyTokens<'font-synthesis-position'> &
  PropertyTokens<'font-synthesis-small-caps'> &
  PropertyTokens<'font-synthesis-style'> &
  PropertyTokens<'font-synthesis-weight'> &
  PropertyTokens<'font-variant'> &
  PropertyTokens<'font-variant-alternates'> &
  PropertyTokens<'font-variant-caps'> &
  PropertyTokens<'font-variant-east-asian'> &
  PropertyTokens<'font-variant-emoji'> &
  PropertyTokens<'font-variant-ligatures'> &
  PropertyTokens<'font-variant-numeric'> &
  PropertyTokens<'font-variant-position'> &
  PropertyTokens<'font-variation-settings'> &
  PropertyTokens<'font-weight'> &
  PropertyTokens<'forced-color-adjust'> &
  PropertyTokens<'grid-auto-columns'> &
  PropertyTokens<'grid-auto-flow'> &
  PropertyTokens<'grid-auto-rows'> &
  PropertyTokens<'grid-column-end'> &
  PropertyTokens<'grid-column-start'> &
  PropertyTokens<'grid-row-end'> &
  PropertyTokens<'grid-row-start'> &
  PropertyTokens<'grid-template-areas'> &
  PropertyTokens<'grid-template-columns'> &
  PropertyTokens<'grid-template-rows'> &
  PropertyTokens<'hanging-punctuation'> &
  PropertyTokens<'height'> &
  PropertyTokens<'hyphenate-character'> &
  PropertyTokens<'hyphenate-limit-chars'> &
  PropertyTokens<'hyphens'> &
  PropertyTokens<'image-orientation'> &
  PropertyTokens<'image-rendering'> &
  PropertyTokens<'image-resolution'> &
  PropertyTokens<'initial-letter'> &
  PropertyTokens<'input-security'> &
  PropertyTokens<'isolation'> &
  PropertyTokens<'justify-content'> &
  PropertyTokens<'justify-items'> &
  PropertyTokens<'justify-self'> &
  PropertyTokens<'justify-tracks'> &
  PropertyTokens<'left'> &
  PropertyTokens<'letter-spacing'> &
  PropertyTokens<'line-break'> &
  PropertyTokens<'line-height'> &
  PropertyTokens<'line-height-step'> &
  PropertyTokens<'list-style-image'> &
  PropertyTokens<'list-style-position'> &
  PropertyTokens<'list-style-type'> &
  PropertyTokens<'margin-bottom'> &
  PropertyTokens<'margin-left'> &
  PropertyTokens<'margin-right'> &
  PropertyTokens<'margin-top'> &
  PropertyTokens<'margin-trim'> &
  PropertyTokens<'mask-border-mode'> &
  PropertyTokens<'mask-border-outset'> &
  PropertyTokens<'mask-border-repeat'> &
  PropertyTokens<'mask-border-slice'> &
  PropertyTokens<'mask-border-source'> &
  PropertyTokens<'mask-border-width'> &
  PropertyTokens<'mask-clip'> &
  PropertyTokens<'mask-composite'> &
  PropertyTokens<'mask-image'> &
  PropertyTokens<'mask-mode'> &
  PropertyTokens<'mask-origin'> &
  PropertyTokens<'mask-position'> &
  PropertyTokens<'mask-repeat'> &
  PropertyTokens<'mask-size'> &
  PropertyTokens<'mask-type'> &
  PropertyTokens<'masonry-auto-flow'> &
  PropertyTokens<'math-depth'> &
  PropertyTokens<'math-shift'> &
  PropertyTokens<'math-style'> &
  PropertyTokens<'max-height'> &
  PropertyTokens<'max-lines'> &
  PropertyTokens<'max-width'> &
  PropertyTokens<'min-height'> &
  PropertyTokens<'min-width'> &
  PropertyTokens<'mix-blend-mode'> &
  PropertyTokens<'motion-distance'> &
  PropertyTokens<'motion-path'> &
  PropertyTokens<'motion-rotation'> &
  PropertyTokens<'object-fit'> &
  PropertyTokens<'object-position'> &
  PropertyTokens<'offset-anchor'> &
  PropertyTokens<'offset-distance'> &
  PropertyTokens<'offset-path'> &
  PropertyTokens<'offset-position'> &
  PropertyTokens<'offset-rotate'> &
  PropertyTokens<'offset-rotation'> &
  PropertyTokens<'opacity'> &
  PropertyTokens<'order'> &
  PropertyTokens<'orphans'> &
  PropertyTokens<'outline-color'> &
  PropertyTokens<'outline-offset'> &
  PropertyTokens<'outline-style'> &
  PropertyTokens<'outline-width'> &
  PropertyTokens<'overflow-anchor'> &
  PropertyTokens<'overflow-clip-box'> &
  PropertyTokens<'overflow-clip-margin'> &
  PropertyTokens<'overflow-wrap'> &
  PropertyTokens<'overflow-x'> &
  PropertyTokens<'overflow-y'> &
  PropertyTokens<'overlay'> &
  PropertyTokens<'overscroll-behavior-x'> &
  PropertyTokens<'overscroll-behavior-y'> &
  PropertyTokens<'padding-bottom'> &
  PropertyTokens<'padding-left'> &
  PropertyTokens<'padding-right'> &
  PropertyTokens<'padding-top'> &
  PropertyTokens<'page'> &
  PropertyTokens<'page-break-after'> &
  PropertyTokens<'page-break-before'> &
  PropertyTokens<'page-break-inside'> &
  PropertyTokens<'paint-order'> &
  PropertyTokens<'perspective'> &
  PropertyTokens<'perspective-origin'> &
  PropertyTokens<'pointer-events'> &
  PropertyTokens<'position'> &
  PropertyTokens<'print-color-adjust'> &
  PropertyTokens<'quotes'> &
  PropertyTokens<'resize'> &
  PropertyTokens<'right'> &
  PropertyTokens<'rotate'> &
  PropertyTokens<'row-gap'> &
  PropertyTokens<'ruby-align'> &
  PropertyTokens<'ruby-merge'> &
  PropertyTokens<'ruby-position'> &
  PropertyTokens<'scale'> &
  PropertyTokens<'scroll-behavior'> &
  PropertyTokens<'scroll-margin-bottom'> &
  PropertyTokens<'scroll-margin-left'> &
  PropertyTokens<'scroll-margin-right'> &
  PropertyTokens<'scroll-margin-top'> &
  PropertyTokens<'scroll-padding-bottom'> &
  PropertyTokens<'scroll-padding-left'> &
  PropertyTokens<'scroll-padding-right'> &
  PropertyTokens<'scroll-padding-top'> &
  PropertyTokens<'scroll-snap-align'> &
  PropertyTokens<'scroll-snap-margin-bottom'> &
  PropertyTokens<'scroll-snap-margin-left'> &
  PropertyTokens<'scroll-snap-margin-right'> &
  PropertyTokens<'scroll-snap-margin-top'> &
  PropertyTokens<'scroll-snap-stop'> &
  PropertyTokens<'scroll-snap-type'> &
  PropertyTokens<'scroll-timeline-axis'> &
  PropertyTokens<'scroll-timeline-name'> &
  PropertyTokens<'scrollbar-color'> &
  PropertyTokens<'scrollbar-gutter'> &
  PropertyTokens<'scrollbar-width'> &
  PropertyTokens<'shape-image-threshold'> &
  PropertyTokens<'shape-margin'> &
  PropertyTokens<'shape-outside'> &
  PropertyTokens<'tab-size'> &
  PropertyTokens<'table-layout'> &
  PropertyTokens<'text-align'> &
  PropertyTokens<'text-align-last'> &
  PropertyTokens<'text-combine-upright'> &
  PropertyTokens<'text-decoration-color'> &
  PropertyTokens<'text-decoration-line'> &
  PropertyTokens<'text-decoration-skip'> &
  PropertyTokens<'text-decoration-skip-ink'> &
  PropertyTokens<'text-decoration-style'> &
  PropertyTokens<'text-decoration-thickness'> &
  PropertyTokens<'text-emphasis-color'> &
  PropertyTokens<'text-emphasis-position'> &
  PropertyTokens<'text-emphasis-style'> &
  PropertyTokens<'text-indent'> &
  PropertyTokens<'text-justify'> &
  PropertyTokens<'text-orientation'> &
  PropertyTokens<'text-overflow'> &
  PropertyTokens<'text-rendering'> &
  PropertyTokens<'text-shadow'> &
  PropertyTokens<'text-size-adjust'> &
  PropertyTokens<'text-transform'> &
  PropertyTokens<'text-underline-offset'> &
  PropertyTokens<'text-underline-position'> &
  PropertyTokens<'text-wrap'> &
  PropertyTokens<'timeline-scope'> &
  PropertyTokens<'top'> &
  PropertyTokens<'touch-action'> &
  PropertyTokens<'transform'> &
  PropertyTokens<'transform-box'> &
  PropertyTokens<'transform-origin'> &
  PropertyTokens<'transform-style'> &
  PropertyTokens<'transition-behavior'> &
  PropertyTokens<'transition-delay'> &
  PropertyTokens<'transition-duration'> &
  PropertyTokens<'transition-property'> &
  PropertyTokens<'transition-timing-function'> &
  PropertyTokens<'translate'> &
  PropertyTokens<'unicode-bidi'> &
  PropertyTokens<'user-select'> &
  PropertyTokens<'vertical-align'> &
  PropertyTokens<'view-timeline-axis'> &
  PropertyTokens<'view-timeline-inset'> &
  PropertyTokens<'view-timeline-name'> &
  PropertyTokens<'view-transition-name'> &
  PropertyTokens<'visibility'> &
  PropertyTokens<'white-space'> &
  PropertyTokens<'white-space-collapse'> &
  PropertyTokens<'white-space-trim'> &
  PropertyTokens<'widows'> &
  PropertyTokens<'width'> &
  PropertyTokens<'will-change'> &
  PropertyTokens<'word-break'> &
  PropertyTokens<'word-spacing'> &
  PropertyTokens<'word-wrap'> &
  PropertyTokens<'writing-mode'> &
  PropertyTokens<'z-index'> &
  PropertyTokens<'zoom'> &
  PropertyTokens<'alignment-baseline'> &
  PropertyTokens<'baseline-shift'> &
  PropertyTokens<'clip'> &
  PropertyTokens<'clip-rule'> &
  PropertyTokens<'color-interpolation'> &
  PropertyTokens<'color-rendering'> &
  PropertyTokens<'dominant-baseline'> &
  PropertyTokens<'fill'> &
  PropertyTokens<'fill-opacity'> &
  PropertyTokens<'fill-rule'> &
  PropertyTokens<'flood-color'> &
  PropertyTokens<'flood-opacity'> &
  PropertyTokens<'glyph-orientation-vertical'> &
  PropertyTokens<'lighting-color'> &
  PropertyTokens<'marker'> &
  PropertyTokens<'marker-end'> &
  PropertyTokens<'marker-mid'> &
  PropertyTokens<'marker-start'> &
  PropertyTokens<'shape-rendering'> &
  PropertyTokens<'stop-color'> &
  PropertyTokens<'stop-opacity'> &
  PropertyTokens<'stroke'> &
  PropertyTokens<'stroke-dasharray'> &
  PropertyTokens<'stroke-dashoffset'> &
  PropertyTokens<'stroke-linecap'> &
  PropertyTokens<'stroke-linejoin'> &
  PropertyTokens<'stroke-miterlimit'> &
  PropertyTokens<'stroke-opacity'> &
  PropertyTokens<'stroke-width'> &
  PropertyTokens<'text-anchor'> &
  PropertyTokens<'vector-effect'> &
  PropertyTokens<'block-overflow'> &
  PropertyTokens<'block-size'> &
  PropertyTokens<'border-block'> &
  PropertyTokens<'border-block-end'> &
  PropertyTokens<'border-block-start'> &
  PropertyTokens<'border-block-color'> &
  PropertyTokens<'border-block-end-color'> &
  PropertyTokens<'border-block-end-style'> &
  PropertyTokens<'border-block-end-width'> &
  PropertyTokens<'border-block-start-color'> &
  PropertyTokens<'border-block-start-style'> &
  PropertyTokens<'border-block-start-width'> &
  PropertyTokens<'border-block-style'> &
  PropertyTokens<'border-block-width'> &
  PropertyTokens<'border-inline'> &
  PropertyTokens<'border-inline-end'> &
  PropertyTokens<'border-inline-start'> &
  PropertyTokens<'border-inline-color'> &
  PropertyTokens<'border-inline-end-color'> &
  PropertyTokens<'border-inline-end-style'> &
  PropertyTokens<'border-inline-end-width'> &
  PropertyTokens<'border-inline-start-color'> &
  PropertyTokens<'border-inline-start-style'> &
  PropertyTokens<'border-inline-start-width'> &
  PropertyTokens<'border-inline-style'> &
  PropertyTokens<'border-inline-width'> &
  PropertyTokens<'contain-intrinsic-block-size'> &
  PropertyTokens<'contain-intrinsic-inline-size'> &
  PropertyTokens<'inline-size'> &
  PropertyTokens<'inset-block'> &
  PropertyTokens<'inset-block-end'> &
  PropertyTokens<'inset-block-start'> &
  PropertyTokens<'inset-inline'> &
  PropertyTokens<'inset-inline-end'> &
  PropertyTokens<'inset-inline-start'> &
  PropertyTokens<'margin-block'> &
  PropertyTokens<'margin-block-end'> &
  PropertyTokens<'margin-block-start'> &
  PropertyTokens<'margin-inline'> &
  PropertyTokens<'margin-inline-end'> &
  PropertyTokens<'margin-inline-start'> &
  PropertyTokens<'max-block-size'> &
  PropertyTokens<'max-inline-size'> &
  PropertyTokens<'min-block-size'> &
  PropertyTokens<'min-inline-size'> &
  PropertyTokens<'overflow-block'> &
  PropertyTokens<'overflow-inline'> &
  PropertyTokens<'overscroll-behavior-block'> &
  PropertyTokens<'overscroll-behavior-inline'> &
  PropertyTokens<'padding-block'> &
  PropertyTokens<'padding-block-end'> &
  PropertyTokens<'padding-block-start'> &
  PropertyTokens<'padding-inline'> &
  PropertyTokens<'padding-inline-end'> &
  PropertyTokens<'padding-inline-start'> &
  PropertyTokens<'scroll-margin-block'> &
  PropertyTokens<'scroll-margin-block-end'> &
  PropertyTokens<'scroll-margin-block-start'> &
  PropertyTokens<'scroll-margin-inline'> &
  PropertyTokens<'scroll-margin-inline-end'> &
  PropertyTokens<'scroll-margin-inline-start'> &
  PropertyTokens<'scroll-padding-block'> &
  PropertyTokens<'scroll-padding-block-end'> &
  PropertyTokens<'scroll-padding-block-start'> &
  PropertyTokens<'scroll-padding-inline'> &
  PropertyTokens<'scroll-padding-inline-end'> &
  PropertyTokens<'scroll-padding-inline-start'>;

interface TokenamiProperties extends Properties {
  [customProperty: `---${string}`]: string | number | undefined;
}

type TokenamiPropertiesPick<P extends keyof Property> = Pick<Property, P> extends infer T
  ? T[keyof T]
  : never;

type TokenamiPropertiesOmit<P extends keyof Property> = Omit<Property, P> extends infer T
  ? T[keyof T]
  : never;

export type {
  TokenamiConfig,
  TokenamiFinalConfig,
  TokenamiProperties,
  TokenamiPropertiesPick,
  TokenamiPropertiesOmit,
};
