name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - run: pnpm typecheck

  test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - name: Install Playwright browsers
        working-directory: visual-tests/tokenami
        run: npx playwright install --with-deps
      - run: pnpm test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_BRANCH: ${{ github.head_ref || github.ref_name }}
          PERCY_PULL_REQUEST: ${{ github.event.pull_request.number }}
          PERCY_TARGET_BRANCH: ${{ github.base_ref }}

  size:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [build, test]
    env:
      CI_JOB_NUMBER: 1
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-repo
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # postinstall script does this
          skip_step: build
